// ── Regulated Second-Level Domains (SLDs) ────────────────────────────────────
// Strictly controlled by Indian and global authorities.
// Cannot be freely registered — only verified entities get them.
export const REGULATED_SLDS = new Set([
  "gov.in", "nic.in", "ac.in", "edu.in", "res.in", "mil.in", "net.in",
  "bank.in", "fin.in", "co.in", "org.in",
  "gov", "mil", "edu", "int",
]);

export const URL_SHORTENERS = new Set([
  "bit.ly", "tinyurl.com", "t.co", "goo.gl", "ow.ly",
  "is.gd", "buff.ly", "ift.tt", "short.ly", "rb.gy",
  "cutt.ly", "shorturl.at", "tiny.cc", "s.id",
  "qr.ae", "b23.ru", "bl.ink", "br.cc", "clck.ru",
  "cli.gs", "cur.lv", "db.tt", "dlvr.it",
  "fur.ly", "go2l.ink", "hubs.ly", "j.mp",
  "lnkd.in", "mcaf.ee", "murl.com", "o.oo7.jp",
  "ping.fm", "post.ly", "prettylinkpro.com",
  "q.gs", "qr.net", "redd.it", "scrnch.me", "short.ie",
  "snipurl.com", "su.pr", "tr.im", "twit.ac", "u.bb",
  "u.to", "url.ie", "urlcut.com", "urlenco.de", "v.gd",
  "virl.com", "vzturl.com", "x.co", "xrl.in", "xurl.jp",
  "yfrog.com", "youtu.be", "z0p.de", "zi.ma",
  "2.gp", "2big.at", "2u.pw", "4ks.net", "4url.cc",
  "lc.chat", "shor.by", "shrinkme.io", "shortto.me",
  "inx.lv", "filoops.info", "virb.com",
  "qrco.de", "t.ly", "waa.ai", "b.link", "han.gl",
]);

export const SUSPICIOUS_TLDS = new Set([
  ".tk", ".ml", ".ga", ".cf", ".gq", ".xyz", ".top", ".click",
  ".win", ".loan", ".download", ".cam", ".stream", ".gdn",
  ".racing", ".bid", ".trade", ".party", ".review", ".men",
  ".date", ".faith", ".accountant", ".science", ".work", ".ninja",
  ".country", ".kim", ".xin", ".bar",
]);

export const BRAND_IMPERSONATION_KEYWORDS = [
  "google", "gmail", "youtube", "facebook", "instagram", "twitter",
  "amazon", "flipkart", "snapdeal", "meesho", "myntra", "nykaa",
  "paytm", "phonepe", "razorpay", "cashfree", "payu",
  "sbi", "hdfc", "icici", "axis", "kotak", "rbl", "pnb", "bob",
  "rbi", "npci",
  "paypal", "venmo", "cashapp", "zelle", "stripe",
  "netflix", "hotstar", "primevideo", "spotify",
  "apple", "icloud", "microsoft", "outlook",
  "whatsapp", "telegram", "truecaller",
  "zomato", "swiggy", "blinkit",
  "olacabs", "uber",
  "uidai", "aadhaar",
  "incometax", "irctc",
  "refund", "cashback", "prize", "winner", "lottery",
  "coinbase", "binance", "bybit", "kucoin", "okx", "wazirx",
  "zerodha", "groww", "upstox",
];

export const BRAND_OFFICIAL_DOMAINS: Record<string, string[]> = {
  google: ["google.com", "google.co.in", "google.org", "accounts.google.com"],
  gmail: ["gmail.com", "mail.google.com"],
  youtube: ["youtube.com", "youtu.be"],
  facebook: ["facebook.com", "fb.com", "meta.com"],
  instagram: ["instagram.com"],
  twitter: ["twitter.com", "x.com"],
  amazon: ["amazon.in", "amazon.com", "amazon.co.uk", "amazon.ae", "amazon.com.au"],
  flipkart: ["flipkart.com"],
  paytm: ["paytm.com", "p.paytm.me", "paytmbank.com"],
  phonepe: ["phonepe.com"],
  razorpay: ["razorpay.com", "rzp.io"],
  paypal: ["paypal.com", "paypal.me"],
  apple: ["apple.com", "appleid.apple.com", "icloud.com"],
  icloud: ["icloud.com", "apple.com"],
  microsoft: ["microsoft.com", "live.com", "outlook.com", "microsoftonline.com"],
  outlook: ["outlook.com", "outlook.live.com", "microsoft.com"],
  netflix: ["netflix.com"],
  spotify: ["spotify.com"],
  whatsapp: ["whatsapp.com"],
  telegram: ["telegram.org", "t.me"],
  sbi: [
    "onlinesbi.com", "sbi.co.in", "sbionline.com", "retail.onlinesbi.sbi",
    "sbicard.com", "sbicards.com", "sbimf.com", "sbigeneral.in",
    "yono.sbi.co.in", "sbi.co.in",
  ],
  hdfc: [
    "hdfcbank.com", "netbanking.hdfc.com", "hdfc.com",
    "hdfclife.com", "hdfcergo.com", "hdfcmf.com", "hdfcsec.com",
    "hdfcpension.com", "hdfcsky.com",
  ],
  icici: [
    "icicibank.com", "iciciprulife.com", "icicilombard.com",
    "icicisec.com", "icicibank.in",
  ],
  axis: ["axisbank.com", "axismf.com", "axisdirect.in", "axisbank.co.in"],
  kotak: ["kotak.com", "kotakbank.com", "kotaksec.com", "kotakmf.com", "kotakgeneral.com"],
  rbl: ["rblbank.com", "rbl.co.in"],
  pnb: ["pnbindia.in", "netpnb.com", "pnbmetlife.com"],
  bob: ["bankofbaroda.in", "bobibanking.com"],
  rbi: ["rbi.org.in"],
  npci: ["npci.org.in", "upi.npci.org.in"],
  irctc: ["irctc.co.in", "irctchelp.in"],
  uidai: ["uidai.gov.in"],
  aadhaar: ["uidai.gov.in"],
  incometax: ["incometax.gov.in", "efiling.incometax.gov.in", "taxpayerservices.tin.nsdl.com"],
  coinbase: ["coinbase.com"],
  binance: ["binance.com"],
  zerodha: ["zerodha.com", "kite.zerodha.com"],
  groww: ["groww.in"],
  upstox: ["upstox.com"],
  zomato: ["zomato.com"],
  swiggy: ["swiggy.com"],
  uber: ["uber.com"],
  stripe: ["stripe.com", "buy.stripe.com"],
  olacabs: ["olacabs.com", "mmt.in"],
  refund: [],
  cashback: [],
  prize: [],
  winner: [],
  lottery: [],
  wazirx: ["wazirx.com"],
  bybit: ["bybit.com"],
  kucoin: ["kucoin.com"],
  okx: ["okx.com"],
};

export const SENSITIVE_PATH_KEYWORDS = [
  "verify-account", "update-kyc", "kyc-update", "complete-kyc",
  "otp-verify", "enter-otp",
  "pan-verify", "pan-card-verify",
  "account-recovery", "recover-account",
  "claim-prize", "claim-reward", "claim-cashback",
  "redeem-reward",
  "income-tax-refund", "tax-refund", "refund-claim",
  "free-recharge", "win-prize",
  "credit-card-apply", "loan-apply", "emi-apply",
  "kyc-complete", "aadhar-link", "aadhar-verify",
];
