import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  wrapper: { marginBottom: 16 },
  card: {
    borderRadius: 20, padding: 22, overflow: "hidden",
    shadowColor: "#000", shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35, shadowRadius: 16, elevation: 12,
    marginBottom: 14, position: "relative",
  },
  decCircleLarge: { position: "absolute", width: 180, height: 180, borderRadius: 90, top: -60, right: -60, opacity: 0.4 },
  decCircleSmall: { position: "absolute", width: 100, height: 100, borderRadius: 50, bottom: -30, left: -20, opacity: 0.3 },
  cardTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 },
  appNameRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  appIconBubble: { width: 28, height: 28, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  appNameText: { fontSize: 13, fontFamily: "Inter_600SemiBold", letterSpacing: 0.3 },
  indiaBadge: { backgroundColor: "rgba(255,255,255,0.12)", borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  indiaBadgeText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: "#FFF" },
  shieldBadge: {
    flexDirection: "row", alignItems: "center", gap: 4,
    backgroundColor: "rgba(74, 222, 128, 0.15)", borderRadius: 10,
    paddingHorizontal: 8, paddingVertical: 3,
    borderWidth: 1, borderColor: "rgba(74, 222, 128, 0.3)",
  },
  shieldText: { fontSize: 12, fontFamily: "Inter_700Bold", color: "#4ADE80", letterSpacing: 0.5 },
  merchantName: { fontSize: 26, fontFamily: "Inter_700Bold", letterSpacing: -0.5, lineHeight: 32, marginBottom: 10 },
  upiRow: { flexDirection: "row", alignItems: "flex-start", gap: 6, marginBottom: 8 },
  upiId: { fontSize: 13, fontFamily: "Inter_400Regular", flex: 1, letterSpacing: 0.2 },
  upiExpandHint: { fontSize: 12, fontFamily: "Inter_600SemiBold", letterSpacing: 0.3, flexShrink: 0 },
  bankRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 6 },
  bankName: { fontSize: 12, fontFamily: "Inter_400Regular" },
  amountChip: { flexDirection: "row", alignItems: "center", gap: 7, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, marginTop: 10, marginBottom: 4, borderWidth: 1, alignSelf: "flex-start" },
  amountText: { fontSize: 18, fontFamily: "Inter_700Bold", color: "#FCD34D" },
  amountLabel: { fontSize: 12, fontFamily: "Inter_400Regular" },
  noteRow: { flexDirection: "row", alignItems: "flex-start", gap: 6, marginTop: 8 },
  noteText: { fontSize: 12, fontFamily: "Inter_400Regular", flex: 1, lineHeight: 17 },
  cardChipLine: { height: 1, borderRadius: 1, marginVertical: 14 },
  cardBottomRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  verifiedRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  verifiedDot: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: "#4ADE80" },
  verifiedText: { fontSize: 12, fontFamily: "Inter_400Regular" },
  regionText: { fontSize: 12, fontFamily: "Inter_600SemiBold", letterSpacing: 0.5 },
  extraFieldsBlock: { marginTop: 10, marginBottom: 2, gap: 5 },
  extraFieldRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  extraFieldLabel: { fontSize: 12, fontFamily: "Inter_500Medium", minWidth: 52, letterSpacing: 0.2 },
  extraFieldValue: { fontSize: 12, fontFamily: "Inter_600SemiBold", flex: 1, letterSpacing: 0.1 },
  actionArea: { gap: 10 },
  payBtn: { borderRadius: 14, overflow: "hidden" },
  payBtnGradient: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, paddingVertical: 14, paddingHorizontal: 20 },
  payBtnText: { fontSize: 15, fontFamily: "Inter_700Bold", color: "#FFFFFF", flex: 1, textAlign: "center" },
  warningBox: {
    flexDirection: "row", alignItems: "flex-start", gap: 6,
    backgroundColor: "rgba(148, 163, 184, 0.06)", borderRadius: 8,
    paddingHorizontal: 10, paddingVertical: 6,
    borderWidth: 1, borderColor: "rgba(148, 163, 184, 0.10)",
  },
  warningText: { fontSize: 12, fontFamily: "Inter_400Regular", color: "#94A3B8", flex: 1, lineHeight: 15 },
  deactivatedBanner: {
    flexDirection: "row", alignItems: "center", gap: 8,
    backgroundColor: "rgba(239,68,68,0.1)", borderRadius: 10, padding: 12,
    borderWidth: 1, borderColor: "rgba(239,68,68,0.25)",
  },
  deactivatedText: { fontSize: 13, fontFamily: "Inter_500Medium", color: "#EF4444", flex: 1 },
});
