import { useState, useCallback } from "react";
import { Alert, Platform, ToastAndroid } from "react-native";
import * as Clipboard from "expo-clipboard";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import * as Print from "expo-print";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Haptics from "@/shared/utils/haptics";
import { captureQrImage } from "@/shared/utils/capture-qr";
import { getRawContent } from "@/features/generator/data/qr-builder";
import type { QrMode } from "@/features/generator/types/form-types";

interface Params {
  qrValue:        string;
  qrMode:         QrMode;
  isBranded:      boolean;
  inputValue:     string;
  selectedPreset: number;
  extraFields:    Record<string, string>;
  svgRef:         React.RefObject<any>;
  showToast:      (msg: string, type?: "success" | "error") => void;
}

function buildPdfHtml(imgSrc: string, contentLabel: string): string {
  const escaped = contentLabel.replace(/</g, "&lt;").replace(/>/g, "&gt;");
  return `<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { display: flex; justify-content: center; align-items: center; min-height: 100vh; background: #ffffff; font-family: Arial, sans-serif; }
      .container { text-align: center; padding: 48px 40px; max-width: 420px; }
      .logo-row { display: flex; align-items: center; justify-content: center; gap: 8px; margin-bottom: 28px; }
      .logo-text { font-size: 15px; font-weight: 700; color: #0A0E17; letter-spacing: 0.5px; }
      .qr-wrap { background: #f8fafc; border-radius: 20px; padding: 24px; display: inline-block; border: 1px solid #e2e8f0; margin-bottom: 24px; }
      img { width: 240px; height: 240px; display: block; }
      .label { font-size: 13px; color: #64748b; word-break: break-all; max-width: 300px; margin: 0 auto 6px; line-height: 1.5; }
      .footer { margin-top: 28px; font-size: 10px; color: #cbd5e1; }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="logo-row">
        <span class="logo-text">BinRo</span>
      </div>
      <div class="qr-wrap">
        <img src="${imgSrc}" alt="QR Code" />
      </div>
      <p class="label">${escaped}</p>
      <p class="footer">Generated by BinRo &bull; Scan to verify safety</p>
    </div>
  </body>
</html>`;
}

export function useQrActions({
  qrValue,
  qrMode,
  isBranded,
  inputValue,
  selectedPreset,
  extraFields,
  svgRef,
  showToast,
}: Params) {
  const [sharingQr,     setSharingQr]     = useState(false);
  const [downloadingPdf, setDownloadingPdf] = useState(false);

  const handleCopy = useCallback(async () => {
    if (!qrValue) return;
    const raw = getRawContent(selectedPreset, inputValue, extraFields);
    await Clipboard.setStringAsync(raw || qrValue);
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    showToast("Copied to clipboard!", "success");
  }, [qrValue, qrMode, isBranded, inputValue, selectedPreset, extraFields, showToast]);

  const handleShare = useCallback(async () => {
    if (!qrValue || sharingQr) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    if (Platform.OS === "web") {
      showToast("Long-press the QR image to save it.", "success");
      return;
    }
    setSharingQr(true);
    try {
      const rawBase64 = await captureQrImage(svgRef);
      const fileUri   = (FileSystem.cacheDirectory ?? "") + `qrguard_${Date.now()}.png`;
      await FileSystem.writeAsStringAsync(fileUri, rawBase64, { encoding: "base64" });
      if (!(await Sharing.isAvailableAsync())) {
        showToast("Sharing is not available on this device.", "error");
        await FileSystem.deleteAsync(fileUri, { idempotent: true });
        return;
      }
      await Sharing.shareAsync(fileUri, {
        mimeType: "image/png", dialogTitle: "Share QR Code", UTI: "public.png",
      });
      await FileSystem.deleteAsync(fileUri, { idempotent: true });
    } catch (e: any) {
      showToast(e?.message || "Could not share the QR code.", "error");
    } finally {
      setSharingQr(false);
    }
  }, [qrValue, sharingQr, svgRef, showToast]);

  const handleDownloadPdf = useCallback(async () => {
    if (!qrValue || downloadingPdf) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    if (Platform.OS === "web") {
      showToast("PDF download is not supported on web.", "error");
      return;
    }
    setDownloadingPdf(true);
    let pdfUri: string | null = null;
    try {
      const rawBase64 = await captureQrImage(svgRef);
      const imgSrc    = `data:image/png;base64,${rawBase64}`;
      const raw       = qrValue;
      const label = raw.length > 60 ? raw.slice(0, 57) + "…" : raw;
      const html  = buildPdfHtml(imgSrc, label);
      const result = await Print.printToFileAsync({ html, base64: false });
      pdfUri = result.uri;

      if (Platform.OS === "android") {
        const SAF      = FileSystem.StorageAccessFramework;
        const fileName = `BinRo_${Date.now()}.pdf`;
        await new Promise<void>((resolve) => {
          Alert.alert(
            "Save PDF to Downloads",
            "Do you want to save this QR code PDF to your Downloads folder?",
            [
              {
                text: "Cancel",
                style: "cancel",
                onPress: () => resolve(),
              },
              {
                text: "Save",
                onPress: async () => {
                  try {
                    const cachedDir = await AsyncStorage.getItem("qrguard_downloads_dir_uri");
                    if (cachedDir) {
                      try {
                        const b64  = await FileSystem.readAsStringAsync(pdfUri!, { encoding: "base64" });
                        const dest = await SAF.createFileAsync(cachedDir, fileName, "application/pdf");
                        await FileSystem.writeAsStringAsync(dest, b64, { encoding: "base64" });
                        ToastAndroid.show("PDF saved to Downloads ✓", ToastAndroid.LONG);
                        resolve();
                        return;
                      } catch {
                        await AsyncStorage.removeItem("qrguard_downloads_dir_uri");
                      }
                    }
                    const downloadsUri  = SAF.getUriForDirectoryInRoot("Download");
                    const permissions   = await SAF.requestDirectoryPermissionsAsync(downloadsUri);
                    if (!permissions.granted) {
                      showToast("Permission denied. PDF was not saved.", "error");
                      resolve();
                      return;
                    }
                    await AsyncStorage.setItem("qrguard_downloads_dir_uri", permissions.directoryUri);
                    const b64  = await FileSystem.readAsStringAsync(pdfUri!, { encoding: "base64" });
                    const dest = await SAF.createFileAsync(permissions.directoryUri, fileName, "application/pdf");
                    await FileSystem.writeAsStringAsync(dest, b64, { encoding: "base64" });
                    ToastAndroid.show("PDF saved to Downloads ✓", ToastAndroid.LONG);
                    resolve();
                  } catch (e: any) {
                    showToast(e?.message || "Could not save PDF to Downloads.", "error");
                    resolve();
                  }
                },
              },
            ],
            { cancelable: true },
          );
        });
      } else {
        if (!(await Sharing.isAvailableAsync())) {
          showToast("Could not save PDF on this device.", "error");
          return;
        }
        await Sharing.shareAsync(pdfUri, {
          mimeType: "application/pdf", dialogTitle: "Save QR Code as PDF", UTI: "com.adobe.pdf",
        });
      }
    } catch (e: any) {
      showToast(e?.message || "Could not generate PDF.", "error");
    } finally {
      if (pdfUri) FileSystem.deleteAsync(pdfUri, { idempotent: true }).catch(() => {});
      setDownloadingPdf(false);
    }
  }, [qrValue, downloadingPdf, qrMode, inputValue, svgRef, showToast]);

  return { sharingQr, downloadingPdf, handleCopy, handleShare, handleDownloadPdf };
}
