import { StyleSheet } from "react-native";
import { type AppColors } from "@/constants/colors";

export function makeStyles(c: AppColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: c.background },
    centered: { flex: 1, alignItems: "center", justifyContent: "center" },
    emptyText: { fontSize: 15, fontFamily: "Inter_500Medium", color: c.textMuted },
    navBar: {
      flexDirection: "row", alignItems: "center", justifyContent: "space-between",
      paddingHorizontal: 16, paddingVertical: 13,
      borderBottomWidth: 1, borderBottomColor: c.surfaceBorder,
    },
    backBtn: {
      width: 40, height: 40, borderRadius: 20,
      backgroundColor: c.surface, borderWidth: 1, borderColor: c.surfaceBorder,
      alignItems: "center", justifyContent: "center",
    },
    navTitle: { fontSize: 18, fontFamily: "Inter_700Bold", color: c.text, flex: 1, textAlign: "center" },
    scroll: { padding: 16, gap: 14 },
    previewCard: {
      backgroundColor: c.surface, borderRadius: 20,
      borderWidth: 1, borderColor: c.surfaceBorder,
      alignItems: "center", paddingVertical: 24, paddingHorizontal: 20,
    },
    qrBg: {
      borderRadius: 16, padding: 12, position: "relative",
    },
    cornerLogoWrapper: { position: "absolute", width: 36, height: 36 },
    cornerLogoImg: { width: 36, height: 36, borderRadius: 8 },
    uuidRow: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 14 },
    uuidText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: c.safe, letterSpacing: 0.5 },
    qrActionRow: { flexDirection: "row", gap: 10, marginTop: 16, width: "100%" },
    qrActionBtn: {
      flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
      paddingVertical: 11, borderRadius: 14, borderWidth: 1,
    },
    qrActionBtnText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
    metaCard: {
      backgroundColor: c.surface, borderRadius: 16,
      borderWidth: 1, borderColor: c.surfaceBorder, padding: 16,
    },
    sectionLabel: {
      fontSize: 11, fontFamily: "Inter_600SemiBold", color: c.textMuted,
      textTransform: "uppercase", letterSpacing: 0.8, marginBottom: 12,
    },
    metaIconWrap: {
      width: 34, height: 34, borderRadius: 10,
      backgroundColor: c.primaryDim, alignItems: "center", justifyContent: "center",
    },
    metaLabel: { fontSize: 10, fontFamily: "Inter_400Regular", color: c.textMuted, marginBottom: 2 },
    metaValue: { fontSize: 15, fontFamily: "Inter_700Bold", color: c.text },
    divider: { height: 1, backgroundColor: c.surfaceBorder, marginVertical: 12 },
    metaContentRow: { marginBottom: 10 },
    lockedRow: { flexDirection: "row", alignItems: "flex-start", gap: 5, marginTop: 3 },
    metaContentValue: { fontSize: 13, fontFamily: "Inter_400Regular", color: c.textSecondary, flex: 1 },
    copyBtn: {
      flexDirection: "row", alignItems: "center", gap: 6,
      backgroundColor: c.surfaceLight, borderRadius: 10, borderWidth: 1, borderColor: c.surfaceBorder,
      paddingHorizontal: 10, paddingVertical: 6, alignSelf: "flex-start", marginTop: 8,
    },
    designHeader: {
      backgroundColor: c.surface, borderRadius: 16, borderWidth: 1,
      borderColor: c.surfaceBorder, padding: 16,
      flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    },
    designHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
    designHeaderText: { fontSize: 15, fontFamily: "Inter_600SemiBold", color: c.text },
    dirtyDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: c.warning, marginLeft: 4 },
    designPanel: {
      backgroundColor: c.surface, borderRadius: 16, borderWidth: 1,
      borderColor: c.surfaceBorder, padding: 16,
      marginTop: -8, borderTopLeftRadius: 0, borderTopRightRadius: 0,
    },
    designLabel: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: c.textSecondary, marginBottom: 8 },
    swatchRow: { flexDirection: "row", gap: 10 },
    swatch: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "transparent" },
    swatchSelected: { borderColor: c.primary },
    logoRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 4 },
    logoPickerBtn: {
      flexDirection: "row", alignItems: "center", gap: 10,
      backgroundColor: c.surfaceLight, borderRadius: 12, padding: 10,
      borderWidth: 1, borderColor: c.surfaceBorder,
    },
    logoThumb: { width: 32, height: 32, borderRadius: 8 },
    logoPickerLabel: { fontSize: 13, fontFamily: "Inter_500Medium", color: c.text },
    positionRow: { flexDirection: "row", gap: 8 },
    positionBtn: {
      paddingVertical: 7, paddingHorizontal: 14, borderRadius: 20,
      backgroundColor: c.surfaceLight, borderWidth: 1, borderColor: c.surfaceBorder,
    },
    positionBtnActive: { backgroundColor: c.primaryDim, borderColor: c.primary },
    positionBtnText: { fontSize: 12, fontFamily: "Inter_500Medium", color: c.textMuted },
    positionBtnTextActive: { color: c.primary },
    saveDesignBtn: {
      flexDirection: "row", alignItems: "center", justifyContent: "center",
      gap: 8, backgroundColor: c.primary, borderRadius: 14, paddingVertical: 13,
    },
    saveDesignBtnText: { fontSize: 15, fontFamily: "Inter_700Bold", color: c.primaryText },
    commentsHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 4 },
    commentCountBadge: {
      backgroundColor: c.primaryDim, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2,
    },
    commentCountText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: c.primary },
    emptyComments: { alignItems: "center", paddingVertical: 36, gap: 8 },
    emptyCommentsText: { fontSize: 15, fontFamily: "Inter_600SemiBold", color: c.textSecondary },
    emptyCommentsSub: { fontSize: 12, fontFamily: "Inter_400Regular", color: c.textMuted },
    commentsList: { gap: 4 },
    commentBlock: {
      backgroundColor: c.surface, borderRadius: 14,
      borderWidth: 1, borderColor: c.surfaceBorder, overflow: "hidden",
    },
    repliesContainer: { borderTopWidth: 1, borderTopColor: c.surfaceBorder, paddingTop: 4 },
    toggleRepliesBtn: { flexDirection: "row", alignItems: "center", gap: 5, paddingVertical: 8, paddingHorizontal: 12 },
    toggleRepliesText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: c.primary },
    replyRow: { flexDirection: "row", paddingHorizontal: 10, paddingBottom: 4 },
    replyLine: { width: 2, backgroundColor: c.primaryDim, borderRadius: 1, marginRight: 8, marginLeft: 8 },
    inputBar: {
      backgroundColor: c.surface, borderTopWidth: 1,
      borderTopColor: c.surfaceBorder, paddingHorizontal: 14, paddingTop: 10,
    },
    replyBanner: {
      flexDirection: "row", alignItems: "center", gap: 6,
      backgroundColor: c.primaryDim, borderRadius: 10,
      paddingHorizontal: 10, paddingVertical: 6, marginBottom: 8,
    },
    replyBannerText: { fontSize: 12, fontFamily: "Inter_500Medium", color: c.textMuted, flex: 1 },
    inputRow: { flexDirection: "row", alignItems: "flex-end", gap: 10 },
    inputAvatar: {
      width: 34, height: 34, borderRadius: 17,
      backgroundColor: c.primaryDim, alignItems: "center", justifyContent: "center", flexShrink: 0,
    },
    inputAvatarText: { fontSize: 14, fontFamily: "Inter_700Bold", color: c.primary },
    commentInput: {
      flex: 1, backgroundColor: c.surfaceLight, borderRadius: 20,
      paddingHorizontal: 14, paddingVertical: 9, fontSize: 14, fontFamily: "Inter_400Regular",
      color: c.text, maxHeight: 100, borderWidth: 1, borderColor: c.surfaceBorder,
    },
    sendBtn: {
      width: 38, height: 38, borderRadius: 19,
      backgroundColor: c.primary, alignItems: "center", justifyContent: "center",
    },
    deactivationMsg: { fontSize: 13, fontFamily: "Inter_400Regular", color: c.textMuted, fontStyle: "italic", marginBottom: 10 },
    toggleActiveBtn: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 14, paddingVertical: 9, borderRadius: 12 },
    toggleActiveBtnOn: { backgroundColor: c.danger },
    toggleActiveBtnOff: { backgroundColor: c.safe },
    toggleActiveBtnText: { fontSize: 13, fontFamily: "Inter_600SemiBold", color: "#fff" },
  });
}
