import { StyleSheet } from "react-native";
import type { AppColors } from "@/shared/constants/colors";

export function makeLegalStyles(colors: AppColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    metaBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 16,
      borderRadius: 18,
      borderWidth: 1,
      marginBottom: 20,
      backgroundColor: colors.surface,
      borderColor: colors.surfaceBorder,
    },
    metaBannerIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primaryDim,
    },
    metaBannerTitle: {
      fontSize: 15,
      fontFamily: "Inter_700Bold",
      color: colors.text,
      marginBottom: 2,
    },
    metaBannerSub: {
      fontSize: 12,
      fontFamily: "Inter_400Regular",
      color: colors.textMuted,
    },
    sectionCard: {
      borderRadius: 20,
      borderWidth: 1,
      padding: 18,
      marginBottom: 16,
      backgroundColor: colors.surface,
      borderColor: colors.surfaceBorder,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 14,
    },
    sectionNum: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primaryDim,
    },
    sectionNumText: {
      fontSize: 14,
      fontFamily: "Inter_700Bold",
      color: colors.primary,
    },
    sectionIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surfaceLight,
    },
    sectionTitle: {
      fontSize: 16,
      fontFamily: "Inter_700Bold",
      color: colors.text,
      flex: 1,
    },
    para: {
      fontSize: 13,
      fontFamily: "Inter_400Regular",
      lineHeight: 20,
      marginBottom: 10,
      color: colors.textSecondary,
    },
    subhead: {
      fontSize: 13,
      fontFamily: "Inter_700Bold",
      marginTop: 10,
      marginBottom: 6,
      color: colors.text,
    },
    bulletRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      marginBottom: 8,
      paddingLeft: 4,
    },
    bulletDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      marginTop: 7,
      backgroundColor: colors.primary,
    },
    bulletText: {
      flex: 1,
      fontSize: 13,
      fontFamily: "Inter_400Regular",
      lineHeight: 19,
      color: colors.textSecondary,
    },
    warningBox: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      marginTop: 10,
      backgroundColor: colors.warningDim,
      borderColor: colors.warning + "35",
    },
    warningText: {
      flex: 1,
      fontSize: 12,
      fontFamily: "Inter_500Medium",
      lineHeight: 18,
      color: colors.warning,
    },
    divider: {
      height: 1,
      marginVertical: 14,
      backgroundColor: colors.surfaceBorder,
    },
  });
}
