/**
 * android-r8.js
 *
 * Enables R8 code shrinking, resource shrinking, and obfuscation for release
 * builds via withAppBuildGradle.
 *
 * What it does:
 *   1. Sets `enableProguardInReleaseBuilds = true` in app/build.gradle
 *   2. Sets `enableShrinkResourcesInReleaseBuilds = true`
 *   3. Upgrades the proguardFiles line to use proguard-android-optimize.txt
 *      (R8 full-mode — better dead-code removal than the default)
 *   4. Copies proguard-rules.pro from project root → android/app/ at prebuild
 *      time so Gradle can find it.
 *
 * Why a plugin (not direct gradle edits):
 *   The `android/` folder is generated by `expo prebuild` and is not committed.
 *   Any direct edits to android/ are wiped on the next prebuild. This plugin
 *   re-applies the changes on every prebuild automatically.
 */

const { withAppBuildGradle, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

function withAndroidR8(config) {
  // ── Step 1: copy proguard-rules.pro into android/app/ at prebuild time ──
  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const src = path.join(cfg.modRequest.projectRoot, "proguard-rules.pro");
      const dest = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "proguard-rules.pro"
      );
      if (fs.existsSync(src)) {
        fs.copyFileSync(src, dest);
      }
      return cfg;
    },
  ]);

  // ── Step 2: patch app/build.gradle to enable R8 for release builds ──────
  config = withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;

    // 2a. Flip enableProguardInReleaseBuilds to true
    //     Expo scaffolds this variable near the top of build.gradle
    gradle = gradle.replace(
      /def\s+enableProguardInReleaseBuilds\s*=\s*false/,
      "def enableProguardInReleaseBuilds = true"
    );

    // 2b. Enable resource shrinking (removes unused drawables/strings)
    //     Insert it after enableProguardInReleaseBuilds if not already there
    if (!gradle.includes("enableShrinkResourcesInReleaseBuilds")) {
      gradle = gradle.replace(
        /def\s+enableProguardInReleaseBuilds\s*=\s*true/,
        "def enableProguardInReleaseBuilds = true\n    def enableShrinkResourcesInReleaseBuilds = true"
      );
    }

    // 2c. Patch the release buildType block to wire shrinkResources
    //     The Expo template has:   minifyEnabled enableProguardInReleaseBuilds
    //     We add:                  shrinkResources enableShrinkResourcesInReleaseBuilds
    if (!gradle.includes("shrinkResources enableShrinkResources")) {
      gradle = gradle.replace(
        /(\bminifyEnabled\s+enableProguardInReleaseBuilds\b)/,
        "$1\n            shrinkResources enableShrinkResourcesInReleaseBuilds"
      );
    }

    // 2d. Upgrade proguardFiles to use the optimised baseline
    //     Default template: getDefaultProguardFile("proguard-android.txt")
    //     We want:          getDefaultProguardFile("proguard-android-optimize.txt")
    gradle = gradle.replace(
      /getDefaultProguardFile\(["']proguard-android\.txt["']\)/g,
      'getDefaultProguardFile("proguard-android-optimize.txt")'
    );

    cfg.modResults.contents = gradle;
    return cfg;
  });

  return config;
}

module.exports = withAndroidR8;
