import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 12,
    overflow: "hidden",
    padding: 18,
    gap: 16,
  },
  scoreHero: { flexDirection: "row", alignItems: "center", gap: 18 },
  scoreRingWrap: { flexShrink: 0 },
  scoreRing: {
    width: 82,
    height: 82,
    borderRadius: 41,
    padding: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  scoreInner: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  scoreNumRow: { flexDirection: "row", alignItems: "baseline" },
  scoreNum: { fontSize: 28, fontFamily: "Inter_700Bold", lineHeight: 34 },
  scorePct: { fontSize: 13, fontFamily: "Inter_700Bold", marginLeft: 1 },
  scoreMeta: { flex: 1, gap: 8 },
  scoreTitle: { fontSize: 17, fontFamily: "Inter_700Bold" },
  scoreLabelBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 100,
    borderWidth: 1,
  },
  scoreLabelText: { fontSize: 12, fontFamily: "Inter_700Bold", letterSpacing: 0.4 },
  firstVoteBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 100,
    borderWidth: 1,
  },
  firstVoteText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },
  voteCount: { fontSize: 12, fontFamily: "Inter_400Regular" },
  scoreBar: { height: 5, borderRadius: 3, overflow: "hidden" },
  scoreBarFillBase: { height: 5, borderRadius: 3, overflow: "hidden" },
  manipBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderRadius: 12,
    padding: 11,
    borderWidth: 1,
  },
  manipText: { flex: 1, fontSize: 12, fontFamily: "Inter_400Regular", lineHeight: 17 },
  statsGrid: {
    flexDirection: "row",
    borderRadius: 14,
    borderWidth: 1,
    overflow: "hidden",
  },
  statCell: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    gap: 3,
  },
  statCellBorder: {
    borderRightWidth: StyleSheet.hairlineWidth,
  },
  statNum: { fontSize: 16, fontFamily: "Inter_700Bold" },
  statLabel: { fontSize: 11, fontFamily: "Inter_600SemiBold", textAlign: "center" },

  voteBreakdown: {
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: 14,
    gap: 10,
  },
  breakdownTitle: {
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    letterSpacing: 1.2,
  },
  breakdownRows: { gap: 8 },
  breakdownRow: { gap: 5 },
  breakdownLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  breakdownLabel: {
    flex: 1,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  breakdownPct: {
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  barTrack: {
    height: 5,
    borderRadius: 3,
    overflow: "hidden",
  },
  barFill: {
    height: 5,
    borderRadius: 3,
  },
});
