import type { ParsedPaymentQr, PaymentSafetyResult, ParsedUpiQr } from "./types";
import { parseAnyPaymentQr } from "./payment-parser";

const VALID_UPI_HANDLES = new Set([
  "okaxis", "okhdfcbank", "okicici", "oksbi",
  "ybl", "ibl", "axl",
  "paytm", "paytmbank",
  "upi", "rbl",
  "hdfcbank", "icici", "sbi", "axisbank",
  "kotak", "idbi", "federal", "indus",
  "boi", "centralbank", "pnb", "bob",
  "indianbank", "syndicatebank", "allbank",
  "aubank", "airtel", "juspay",
  "freecharge", "mobikwik",
  "yapl", "timecosmos",
  "rajgovhdfcbank", "dlb", "mahb",
  "kvb", "sib", "cbin",
  "cnrb", "cub", "dcb",
  "equitas", "esaf", "fino",
  "idfc", "ikwik", "idfcbank",
  "uco", "uboi", "ubi",
  "vijb", "barodampay", "myicici",
  "naviaxis", "nsdl",
  "pingpay", "postbank",
  "qb", "rblbank", "saraswat",
  "scb", "scmb", "shriramhfl",
  "tjsb", "ucobank", "ujjivan",
  "utbi", "zoicici", "waaxis",
  "ptaxis", "pthdfc", "ptyes",
  "abfspay", "apl", "abhy",
  "bhanix", "bdbl", "bypl",
  "cmsidfc", "csb", "dnsbank",
  "fbl", "hsbc", "iob",
  "jkb", "karb", "kbl",
  "lvb", "mahagrambank", "nkgsb",
  "yesbankltd", "zinghr",
]);

const UPI_SUSPICIOUS_NAME_KEYWORDS = [
  "google", "paytm", "amazon", "flipkart", "phonepe",
  "sbi", "hdfc", "icici", "axis", "rbi", "income tax",
  "pm india", "modi", "support", "helpline", "refund",
  "lottery", "winner", "prize", "cashback", "free",
  "bank", "govt", "government", "police", "cbi", "uidai",
  "customs", "covid", "relief", "subsidy", "benefit",
  "meesho", "nykaa", "myntra",
];

const UPI_BRANDED_HANDLES: Record<string, string[]> = {
  google: ["okaxis", "okhdfcbank", "okicici", "oksbi"],
  paytm: ["paytm", "paytmbank"],
  phonepe: ["ybl", "ibl", "axl"],
  amazon: ["yapl"],
  sbi: ["oksbi", "sbi"],
  hdfc: ["okhdfcbank", "hdfcbank"],
  icici: ["okicici", "icici"],
  axis: ["okaxis", "axisbank"],
  bank: [],
  govt: [],
};

export function analyzeAnyPaymentQr(parsed: ParsedPaymentQr): PaymentSafetyResult {
  const warnings: string[] = [];
  let riskLevel: "safe" | "caution" | "dangerous" = "safe";

  function bump(level: "caution" | "dangerous") {
    if (level === "dangerous") riskLevel = "dangerous";
    else if (riskLevel === "safe") riskLevel = "caution";
  }

  if (parsed.appCategory === "crypto") {
    warnings.push(`Crypto payment: ${parsed.appDisplayName} — transactions are irreversible`);
    warnings.push("Verify the wallet address character by character — one wrong digit means lost funds forever");
    if (parsed.isAmountPreFilled) {
      warnings.push(`Pre-filled amount detected — only pay if you intended this`);
    }
    const addr = parsed.recipientId;
    if (addr && (addr.length < 20 || addr.length > 100)) {
      warnings.push("Wallet address length looks unusual — double check before sending");
      bump("dangerous");
    }
    bump("caution");
    return { isSuspicious: true, warnings, riskLevel, appInfo: parsed.appDisplayName };
  }

  if (parsed.appCategory === "upi_india") {
    if (!parsed.bankHandle) {
      warnings.push("No bank handle found in VPA — verify this is a valid UPI address");
      bump("caution");
    } else if (!VALID_UPI_HANDLES.has(parsed.bankHandle)) {
      warnings.push(`Unknown bank handle "@${parsed.bankHandle}" — verify before paying`);
      bump("caution");
    }

    if (!parsed.recipientName || parsed.recipientName.trim() === "") {
      warnings.push("No payee name — legitimate merchants always show their name");
      bump("caution");
    } else {
      const lowerName = parsed.recipientName.toLowerCase();
      for (const kw of UPI_SUSPICIOUS_NAME_KEYWORDS) {
        if (lowerName.includes(kw)) {
          const official = UPI_BRANDED_HANDLES[kw];
          if (!official || !official.includes(parsed.bankHandle || "")) {
            warnings.push(`Payee name contains "${kw}" but VPA doesn't match — possible impersonation`);
            bump("dangerous");
            break;
          }
        }
      }
    }

    if (parsed.isAmountPreFilled && parsed.amount) {
      const amt = parseFloat(parsed.amount);
      if (amt > 50000) {
        warnings.push(`Large pre-filled amount: ₹${amt.toLocaleString("en-IN")} — only pay if YOU initiated this`);
        bump("dangerous");
      } else if (amt > 0) {
        warnings.push(`Amount pre-filled: ₹${amt.toLocaleString("en-IN")} — confirm before paying`);
        bump("caution");
      }
    }

    const vpaLocal = (parsed.vpa || parsed.recipientId).split("@")[0];
    if (vpaLocal.length > 20) {
      warnings.push("VPA identifier is unusually long — could be auto-generated by scammers");
      bump("caution");
    }
  }

  if (["global_wallet", "us_payment"].includes(parsed.appCategory)) {
    if (!parsed.recipientId) {
      warnings.push(`No recipient ID found in ${parsed.appDisplayName} QR`);
      bump("caution");
    }
    if (parsed.isAmountPreFilled && parsed.amount) {
      warnings.push(`Pre-filled amount in ${parsed.appDisplayName} — verify the exact recipient before sending`);
      bump("caution");
    }
  }

  if (["southeast_asia", "korea", "japan", "singapore_malaysia", "thailand"].includes(parsed.appCategory)) {
    if (!parsed.recipientId || parsed.recipientId.trim().length < 4) {
      warnings.push(`Recipient ID is missing or very short in ${parsed.appDisplayName} QR`);
      bump("caution");
    }
    if (parsed.isAmountPreFilled) {
      warnings.push(`Pre-set amount detected — confirm the payee and amount before proceeding`);
      bump("caution");
    }
  }

  if (parsed.app === "sepa_transfer") {
    if (!parsed.recipientId || !parsed.recipientId.startsWith("IBAN")) {
      if (!parsed.recipientId) {
        warnings.push("IBAN not found in SEPA QR — invalid format");
        bump("caution");
      }
    }
    if (parsed.amount && parseFloat(parsed.amount) > 5000) {
      warnings.push(`Large SEPA transfer: €${parseFloat(parsed.amount).toFixed(2)} — verify before authorizing`);
      bump("caution");
    }
  }

  if (parsed.app === "emv_generic") {
    warnings.push("Generic payment QR detected — confirm the payment network and merchant before paying");
    bump("caution");
  }

  if (parsed.app === "unknown_payment" || parsed.appCategory === "other") {
    warnings.push("Payment QR detected — the app or bank is not in our known registry, so verify the merchant carefully before paying");
    if (parsed.isAmountPreFilled && parsed.amount) {
      const amt = parseFloat(parsed.amount);
      if (amt > 0) {
        warnings.push(`Pre-filled amount: ${parsed.currency || ""} ${amt.toLocaleString()} — only pay if YOU initiated this`);
        bump(amt > 50000 ? "dangerous" : "caution");
      }
    }
    if (!parsed.recipientId || parsed.recipientId.length < 3) {
      warnings.push("No recipient ID found — do not pay without verifying who receives the money");
      bump("caution");
    }
    bump("caution");
  }

  if (parsed.appCategory === "china") {
    warnings.push(`${parsed.appDisplayName} QR: verify you are paying the correct merchant`);
    bump("caution");
  }

  if (parsed.app === "pix") {
    if (parsed.isAmountPreFilled && parsed.amount) {
      const amt = parseFloat(parsed.amount);
      if (amt > 1000) {
        warnings.push(`Pix transfer: R$${amt.toFixed(2)} — Pix is instant and irreversible, confirm the key`);
        bump("caution");
      }
    }
  }

  return {
    isSuspicious: warnings.length > 0,
    warnings,
    riskLevel,
    appInfo: parsed.appDisplayName,
  };
}

export function parseUpiQr(content: string): ParsedUpiQr | null {
  const parsed = parseAnyPaymentQr(content);
  if (!parsed || parsed.appCategory !== "upi_india") return null;
  return {
    vpa: parsed.vpa || parsed.recipientId,
    payeeName: parsed.recipientName || "",
    amount: parsed.amount || null,
    currency: parsed.currency || "INR",
    transactionNote: parsed.note || null,
    merchantCategory: null,
    bankHandle: parsed.bankHandle || "",
    isAmountPreFilled: parsed.isAmountPreFilled,
  };
}

export function analyzePaymentQr(parsed: ParsedUpiQr): PaymentSafetyResult {
  const universal: ParsedPaymentQr = {
    app: "upi",
    appDisplayName: "UPI",
    appCategory: "upi_india",
    region: "India",
    recipientId: parsed.vpa,
    recipientName: parsed.payeeName,
    amount: parsed.amount || undefined,
    currency: parsed.currency,
    note: parsed.transactionNote || undefined,
    rawContent: "",
    isAmountPreFilled: parsed.isAmountPreFilled,
    bankHandle: parsed.bankHandle,
    vpa: parsed.vpa,
  };
  return analyzeAnyPaymentQr(universal);
}
