import { StyleSheet, Platform } from "react-native";

export const DARK = {
  background: "#0a0e17",
  surface: "#111827",
  surfaceBorder: "rgba(255,255,255,0.08)",
  text: "#f8fafc",
  textSecondary: "#94a3b8",
  textMuted: "#64748b",
  primary: "#00d4ff",
  danger: "#ef4444",
  safe: "#22c55e",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DARK.background,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  iconCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "rgba(239,68,68,0.12)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: DARK.text,
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 15,
    color: DARK.textSecondary,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
    maxWidth: 320,
  },
  errorBox: {
    width: "100%",
    backgroundColor: DARK.surface,
    borderWidth: 1,
    borderColor: DARK.surfaceBorder,
    borderRadius: 12,
    padding: 14,
    marginBottom: 28,
  },
  errorBoxLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: DARK.danger,
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  errorBoxText: {
    fontSize: 12,
    color: DARK.textSecondary,
    lineHeight: 18,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  actions: {
    width: "100%",
    gap: 10,
    alignItems: "center",
  },
  primaryBtn: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: DARK.primary,
    paddingVertical: 15,
    borderRadius: 14,
  },
  primaryBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#000",
  },
  secondaryBtn: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: DARK.surface,
    borderWidth: 1,
    borderColor: DARK.surfaceBorder,
    paddingVertical: 14,
    borderRadius: 14,
  },
  secondaryBtnText: {
    fontSize: 15,
    fontWeight: "600",
    color: DARK.textSecondary,
  },
  ghostBtn: {
    paddingVertical: 10,
  },
  ghostBtnText: {
    fontSize: 13,
    color: DARK.textMuted,
    textDecorationLine: "underline",
  },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    marginBottom: 16,
    gap: 4,
  },
  backText: {
    fontSize: 15,
    color: DARK.textSecondary,
  },
  reportContent: {
    paddingBottom: 40,
  },
  reportTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: DARK.text,
    marginBottom: 8,
  },
  reportSubtitle: {
    fontSize: 14,
    color: DARK.textSecondary,
    lineHeight: 21,
    marginBottom: 20,
  },
  errorPreview: {
    backgroundColor: DARK.surface,
    borderWidth: 1,
    borderColor: DARK.surfaceBorder,
    borderRadius: 10,
    padding: 12,
    marginBottom: 20,
  },
  errorPreviewLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: DARK.danger,
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  errorPreviewText: {
    fontSize: 12,
    color: DARK.textSecondary,
    lineHeight: 17,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: DARK.textSecondary,
    marginBottom: 8,
  },
  input: {
    backgroundColor: DARK.surface,
    borderWidth: 1,
    borderColor: DARK.surfaceBorder,
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    color: DARK.text,
    minHeight: 110,
    lineHeight: 20,
  },
  charCount: {
    fontSize: 11,
    color: DARK.textMuted,
    textAlign: "right",
    marginTop: 4,
    marginBottom: 16,
  },
  submitErrorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(239,68,68,0.1)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.25)",
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
  },
  submitErrorText: {
    flex: 1,
    fontSize: 13,
    color: DARK.danger,
    lineHeight: 18,
  },
  successBox: {
    alignItems: "center",
    paddingVertical: 40,
    gap: 12,
  },
  successIcon: {
    marginBottom: 8,
  },
  successTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: DARK.text,
  },
  successMsg: {
    fontSize: 14,
    color: DARK.textSecondary,
    textAlign: "center",
    lineHeight: 21,
    marginBottom: 20,
    maxWidth: 280,
  },
});
