import type { PaymentAppId, ParsedPaymentQr } from "../types";

export interface AppDef {
  id: PaymentAppId;
  displayName: string;
  category: ParsedPaymentQr["appCategory"];
  region: string;
  schemes: string[];
  urlPatterns: string[];
  trustedDomains?: string[];
}

export const PAYMENT_APP_REGISTRY: AppDef[] = [
  { id: "upi", displayName: "UPI", category: "upi_india", region: "India", schemes: ["upi://pay"], urlPatterns: [], trustedDomains: ["upi.npci.org.in"] },
  { id: "gpay_india", displayName: "Google Pay (GPay)", category: "upi_india", region: "India", schemes: ["tez://upi", "gpay://upi"], urlPatterns: ["pay.google.com/gp/p/ui"], trustedDomains: ["pay.google.com"] },
  { id: "phonepe", displayName: "PhonePe", category: "upi_india", region: "India", schemes: ["phonepe://pay", "phonepe://upi"], urlPatterns: ["phonepe.com/transact"], trustedDomains: ["phonepe.com"] },
  { id: "paytm", displayName: "Paytm", category: "upi_india", region: "India", schemes: ["paytm://"], urlPatterns: ["p.paytm.me", "paytm.com/qr"], trustedDomains: ["paytm.com", "p.paytm.me"] },
  { id: "bhim", displayName: "BHIM", category: "upi_india", region: "India", schemes: ["bhim://"], urlPatterns: [], trustedDomains: ["bhimupi.org.in"] },
  { id: "amazon_pay", displayName: "Amazon Pay", category: "upi_india", region: "India", schemes: ["amazonpay://", "amazon://pay"], urlPatterns: ["amazon.in/pay", "amazonpay.in"], trustedDomains: ["amazon.in", "amazonpay.in"] },
  { id: "cred", displayName: "CRED Pay", category: "upi_india", region: "India", schemes: ["cred://", "credpay://"], urlPatterns: ["cred.club/pay"], trustedDomains: ["cred.club"] },
  { id: "freecharge", displayName: "FreeCharge", category: "upi_india", region: "India", schemes: ["freecharge://"], urlPatterns: ["freecharge.in"], trustedDomains: ["freecharge.in"] },
  { id: "mobikwik", displayName: "MobiKwik", category: "upi_india", region: "India", schemes: ["mobikwik://"], urlPatterns: ["mobikwik.com"], trustedDomains: ["mobikwik.com"] },
  { id: "airtel_money", displayName: "Airtel Payments Bank", category: "upi_india", region: "India", schemes: ["airtelpe://", "airtelmoney://"], urlPatterns: ["airtelpebank.in", "airtelpayments"], trustedDomains: ["airtelpebank.in"] },
  { id: "jiomoney", displayName: "JioMoney", category: "upi_india", region: "India", schemes: ["jiomoney://"], urlPatterns: ["jiomoney.com"], trustedDomains: ["jiomoney.com"] },
  { id: "razorpay", displayName: "Razorpay", category: "india_wallet", region: "India", schemes: ["razorpay://"], urlPatterns: ["rzp.io", "razorpay.com/payment"], trustedDomains: ["razorpay.com", "rzp.io"] },
  { id: "cashfree", displayName: "Cashfree", category: "india_wallet", region: "India", schemes: ["cashfree://"], urlPatterns: ["cashfree.com"], trustedDomains: ["cashfree.com"] },
  { id: "payu", displayName: "PayU", category: "india_wallet", region: "India", schemes: ["payu://"], urlPatterns: ["payu.in", "secure.payu.in"], trustedDomains: ["payu.in"] },
  { id: "bajaj_pay", displayName: "Bajaj Pay", category: "upi_india", region: "India", schemes: ["bajajpay://"], urlPatterns: ["bajajfinserv.in/pay"], trustedDomains: ["bajajfinserv.in"] },
  { id: "yono_sbi", displayName: "YONO SBI", category: "upi_india", region: "India", schemes: ["yono://"], urlPatterns: ["yono.sbi.co.in"], trustedDomains: ["yono.sbi.co.in", "sbi.co.in"] },
  { id: "imobile_pay", displayName: "iMobile Pay (ICICI)", category: "upi_india", region: "India", schemes: ["imobilepay://"], urlPatterns: ["icicibank.com/imobile"], trustedDomains: ["icicibank.com"] },
  { id: "slice", displayName: "Slice", category: "upi_india", region: "India", schemes: ["slice://"], urlPatterns: ["sliceit.in"], trustedDomains: ["sliceit.in"] },
  { id: "juspay", displayName: "JusPay", category: "india_wallet", region: "India", schemes: ["juspay://"], urlPatterns: ["juspay.in"], trustedDomains: ["juspay.in"] },
  { id: "hdfc_bank", displayName: "HDFC Bank", category: "upi_india", region: "India", schemes: ["hdfcbank://", "payzapp://", "hdfc://", "hdfcpay://", "smarthubbusiness://"], urlPatterns: ["hdfcbank.com/pay", "payzapp.in", "smartpay.hdfcbank.com", "hdfcbanksmarthub.com", "vyapar.hdfcbank.com"], trustedDomains: ["hdfcbank.com", "payzapp.in"] },
  { id: "bharatpe", displayName: "BharatPe", category: "upi_india", region: "India", schemes: ["bharatpe://", "swipe://"], urlPatterns: ["bharatpe.com", "bharatpe.one", "merchants.bharatpe.com"], trustedDomains: ["bharatpe.com", "bharatpe.one"] },
  { id: "axis_pay", displayName: "Axis Pay", category: "upi_india", region: "India", schemes: ["axispay://", "axisbank://", "axis://"], urlPatterns: ["axisbank.com/pay", "axisbank.com/mobile-banking", "axispay.in", "open.axisbank.com"], trustedDomains: ["axisbank.com", "axispay.in"] },
  { id: "navi", displayName: "Navi", category: "upi_india", region: "India", schemes: ["navi://"], urlPatterns: ["navi.com/pay", "navi.com/upi"], trustedDomains: ["navi.com"] },
  { id: "superapp", displayName: "SuperApp", category: "upi_india", region: "India", schemes: ["superapp://", "superfin://"], urlPatterns: ["superfin.money", "fincarebank.in"], trustedDomains: ["superfin.money", "fincarebank.in"] },
  { id: "pockets_icici", displayName: "Pockets (ICICI Bank)", category: "upi_india", region: "India", schemes: ["pockets://", "icicipockets://"], urlPatterns: ["pockets.icicibank.com", "icicibank.com/pockets"], trustedDomains: ["icicibank.com"] },
  { id: "kotak_pay", displayName: "Kotak Pay", category: "upi_india", region: "India", schemes: ["kotak://", "kotakpay://", "kotak811://"], urlPatterns: ["kotak.com/pay", "kotak811.com", "m.kotak.com/payment"], trustedDomains: ["kotak.com", "kotak811.com"] },
  { id: "bob_world", displayName: "BOB World Pay", category: "upi_india", region: "India", schemes: ["bobworld://", "bankofbaroda://", "baroda://", "barodampay://"], urlPatterns: ["bankofbaroda.in/pay", "bobworld.in"], trustedDomains: ["bankofbaroda.in"] },
  { id: "idfcfirst", displayName: "IDFC FIRST Bank", category: "upi_india", region: "India", schemes: ["idfcfirst://", "idfcfirstbank://", "idfcbank://"], urlPatterns: ["idfcfirstbank.com/pay", "idfcbank.com/pay"], trustedDomains: ["idfcfirstbank.com", "idfcbank.com"] },
  { id: "yes_pay", displayName: "Yes Pay (Yes Bank)", category: "upi_india", region: "India", schemes: ["yespay://", "yesbank://", "yesbankpay://"], urlPatterns: ["yesbank.in/pay", "yespay.in"], trustedDomains: ["yesbank.in", "yespay.in"] },
  { id: "fi_money", displayName: "Fi Money", category: "upi_india", region: "India", schemes: ["fi://", "fimoney://"], urlPatterns: ["fi.money/pay", "epifi.com", "fi.money/upi"], trustedDomains: ["fi.money", "epifi.com"] },
  { id: "jupiter_money", displayName: "Jupiter Money", category: "upi_india", region: "India", schemes: ["jupiter://", "jupitermoney://"], urlPatterns: ["jupitermoney.com", "jupiter.money/pay"], trustedDomains: ["jupitermoney.com", "jupiter.money"] },
  { id: "groww_pay", displayName: "Groww Pay", category: "upi_india", region: "India", schemes: ["groww://"], urlPatterns: ["groww.in/pay", "groww.in/upi"], trustedDomains: ["groww.in"] },
  { id: "indpay", displayName: "IndPay (Indian Bank)", category: "upi_india", region: "India", schemes: ["indianbank://", "indpay://"], urlPatterns: ["indianbank.in/pay", "indianbank.co.in"], trustedDomains: ["indianbank.in"] },
  { id: "canara_bank", displayName: "Canara ai1", category: "upi_india", region: "India", schemes: ["canara://", "canpay://", "canarabank://"], urlPatterns: ["canarabank.in/pay", "canarabank.com"], trustedDomains: ["canarabank.in", "canarabank.com"] },
  { id: "union_bank", displayName: "Vyom (Union Bank)", category: "upi_india", region: "India", schemes: ["unionbank://", "vyom://", "uboi://"], urlPatterns: ["unionbankofindia.co.in/pay", "unionbank.co.in"], trustedDomains: ["unionbankofindia.co.in"] },
  { id: "rbl_bank", displayName: "RBL MoBank", category: "upi_india", region: "India", schemes: ["rbl://", "rblmobank://", "rblbank://"], urlPatterns: ["rblbank.com/pay"], trustedDomains: ["rblbank.com"] },
  { id: "pnb_one", displayName: "PNB ONE", category: "upi_india", region: "India", schemes: ["pnb://", "pnbone://", "pnbmobilebanking://"], urlPatterns: ["pnbindia.in/pay", "pnbindia.in"], trustedDomains: ["pnbindia.in"] },
  { id: "indus_pay", displayName: "IndusPay (IndusInd Bank)", category: "upi_india", region: "India", schemes: ["induspay://", "indusmobile://", "indusind://"], urlPatterns: ["indusmobilebanking.com", "indusind.com/pay"], trustedDomains: ["indusind.com", "indusmobilebanking.com"] },
  { id: "bharatqr", displayName: "BharatQR (NPCI)", category: "upi_india", region: "India", schemes: ["bharatqr://"], urlPatterns: ["bharatqr.com", "npci.org.in/bharatqr"], trustedDomains: ["bharatqr.com", "npci.org.in"] },
  { id: "alipay", displayName: "Alipay (支付宝)", category: "china", region: "China", schemes: ["alipay://", "alipays://"], urlPatterns: ["qr.alipay.com", "global.alipay.com", "intl.alipay.com"], trustedDomains: ["alipay.com", "alipayobjects.com"] },
  { id: "wechat_pay", displayName: "WeChat Pay (微信支付)", category: "china", region: "China", schemes: ["wxp://", "weixin://wxpay", "weixin://dl/pay"], urlPatterns: ["wx.tenpay.com", "weixin.qq.com/q/", "qr.weixin.qq.com"], trustedDomains: ["weixin.qq.com", "tenpay.com"] },
  { id: "paypal", displayName: "PayPal", category: "global_wallet", region: "Global", schemes: ["paypal://"], urlPatterns: ["paypal.me/", "paypal.com/qrcodes", "paypal.com/paypalme"], trustedDomains: ["paypal.com", "paypal.me"] },
  { id: "venmo", displayName: "Venmo", category: "us_payment", region: "USA", schemes: ["venmo://"], urlPatterns: ["venmo.com/u/", "venmo.com/code"], trustedDomains: ["venmo.com"] },
  { id: "cash_app", displayName: "Cash App", category: "us_payment", region: "USA", schemes: ["cashapp://"], urlPatterns: ["cash.app/$"], trustedDomains: ["cash.app"] },
  { id: "zelle", displayName: "Zelle", category: "us_payment", region: "USA", schemes: ["zelle://"], urlPatterns: ["zellepay.com"], trustedDomains: ["zellepay.com"] },
  { id: "stripe", displayName: "Stripe", category: "us_payment", region: "Global", schemes: [], urlPatterns: ["buy.stripe.com/", "checkout.stripe.com/"], trustedDomains: ["stripe.com", "buy.stripe.com"] },
  { id: "square", displayName: "Square", category: "us_payment", region: "Global", schemes: [], urlPatterns: ["square.link/", "squareup.com/pay", "squareup.com/appointments"], trustedDomains: ["squareup.com", "square.link"] },
  { id: "grabpay", displayName: "GrabPay", category: "southeast_asia", region: "SE Asia", schemes: ["grab://", "grabpay://"], urlPatterns: ["grab.com/pay", "grbpay.com", "app.grab.com"], trustedDomains: ["grab.com"] },
  { id: "gopay", displayName: "GoPay (GoJek)", category: "southeast_asia", region: "Indonesia", schemes: ["gojek://", "gopay://"], urlPatterns: ["link.gojek.com", "gojek.com/gopay"], trustedDomains: ["gojek.com", "link.gojek.com"] },
  { id: "ovo", displayName: "OVO", category: "southeast_asia", region: "Indonesia", schemes: ["ovo://"], urlPatterns: ["app.ovo.id", "ovo.id/pay"], trustedDomains: ["ovo.id"] },
  { id: "dana", displayName: "DANA", category: "southeast_asia", region: "Indonesia", schemes: ["dana://"], urlPatterns: ["link.dana.id", "dana.id/pay"], trustedDomains: ["dana.id"] },
  { id: "linkaja", displayName: "LinkAja", category: "southeast_asia", region: "Indonesia", schemes: ["linkaja://"], urlPatterns: ["linkaja.id"], trustedDomains: ["linkaja.id"] },
  { id: "shopeepay", displayName: "ShopeePay", category: "southeast_asia", region: "SE Asia", schemes: ["shopeepay://"], urlPatterns: ["shopeepay.com", "shopee.com/universal-link/pay"], trustedDomains: ["shopeepay.com", "shopee.com"] },
  { id: "line_pay", displayName: "LINE Pay", category: "southeast_asia", region: "SE Asia", schemes: ["linepay://", "line://payment"], urlPatterns: ["pay.line.me", "line.me/R/pay"], trustedDomains: ["pay.line.me", "line.me"] },
  { id: "truemoney", displayName: "TrueMoney Wallet", category: "southeast_asia", region: "Thailand", schemes: ["truemoney://", "truemoneygo://"], urlPatterns: ["truemoney.com"], trustedDomains: ["truemoney.com"] },
  { id: "momo_vn", displayName: "MoMo", category: "southeast_asia", region: "Vietnam", schemes: ["momo://"], urlPatterns: ["momo.vn/pay", "nhantien.momo.vn"], trustedDomains: ["momo.vn"] },
  { id: "zalopay", displayName: "ZaloPay", category: "southeast_asia", region: "Vietnam", schemes: ["zalopay://"], urlPatterns: ["zalopay.vn"], trustedDomains: ["zalopay.vn"] },
  { id: "gcash", displayName: "GCash", category: "southeast_asia", region: "Philippines", schemes: ["gcash://"], urlPatterns: ["gcash.com/pay", "m.me/gcashofficial"], trustedDomains: ["gcash.com"] },
  { id: "maya", displayName: "Maya (PayMaya)", category: "southeast_asia", region: "Philippines", schemes: ["maya://", "paymaya://"], urlPatterns: ["maya.ph/pay", "paymaya.com"], trustedDomains: ["maya.ph", "paymaya.com"] },
  { id: "kakaopay", displayName: "KakaoPay", category: "korea", region: "South Korea", schemes: ["kakaopay://"], urlPatterns: ["qr.kakaopay.com", "kakaopay.com/qr"], trustedDomains: ["kakaopay.com"] },
  { id: "toss", displayName: "Toss", category: "korea", region: "South Korea", schemes: ["supertoss://", "toss://"], urlPatterns: ["toss.im/transfer", "toss.im/pay"], trustedDomains: ["toss.im"] },
  { id: "naverpay", displayName: "Naver Pay", category: "korea", region: "South Korea", schemes: ["naverpay://"], urlPatterns: ["pay.naver.com"], trustedDomains: ["pay.naver.com"] },
  { id: "payco", displayName: "PAYCO", category: "korea", region: "South Korea", schemes: ["payco://"], urlPatterns: ["payco.com"], trustedDomains: ["payco.com"] },
  { id: "paypay_jp", displayName: "PayPay", category: "japan", region: "Japan", schemes: ["paypay://"], urlPatterns: ["qr.paypay.ne.jp", "pay.paypay.ne.jp"], trustedDomains: ["paypay.ne.jp"] },
  { id: "merpay", displayName: "Merpay", category: "japan", region: "Japan", schemes: ["merpay://"], urlPatterns: ["merpay.com/pay"], trustedDomains: ["merpay.com"] },
  { id: "rakuten_pay", displayName: "Rakuten Pay", category: "japan", region: "Japan", schemes: ["rakutenpay://"], urlPatterns: ["pay.rakuten.co.jp", "pay.r10s.jp"], trustedDomains: ["rakuten.co.jp"] },
  { id: "d_payment", displayName: "d払い (d Payment)", category: "japan", region: "Japan", schemes: ["dpay://", "d-payment://"], urlPatterns: ["service.smt.docomo.ne.jp/keitai_payment"], trustedDomains: ["docomo.ne.jp"] },
  { id: "au_pay", displayName: "au PAY", category: "japan", region: "Japan", schemes: ["aupay://"], urlPatterns: ["pay.au.com", "aupay.wallet.auone.jp"], trustedDomains: ["au.com", "auone.jp"] },
  { id: "paylah", displayName: "DBS PayLah!", category: "singapore_malaysia", region: "Singapore", schemes: ["paylah://", "dbspaylah://"], urlPatterns: ["paylah.dbs.com", "dbs.com/lah"], trustedDomains: ["dbs.com", "dbs.com.sg"] },
  { id: "duitnow", displayName: "DuitNow", category: "singapore_malaysia", region: "Malaysia", schemes: ["duitnow://"], urlPatterns: ["duitnow.my", "jompay.my"], trustedDomains: ["duitnow.my"] },
  { id: "touchngo", displayName: "Touch 'n Go eWallet", category: "singapore_malaysia", region: "Malaysia", schemes: ["tng://", "tng-ewallet://", "tngdigital://"], urlPatterns: ["tngdigital.com.my", "touchngo.com.my"], trustedDomains: ["touchngo.com.my", "tngdigital.com.my"] },
  { id: "boost_my", displayName: "Boost", category: "singapore_malaysia", region: "Malaysia", schemes: ["boost://"], urlPatterns: ["boost.com.my"], trustedDomains: ["boost.com.my"] },
  { id: "promptpay", displayName: "PromptPay", category: "thailand", region: "Thailand", schemes: [], urlPatterns: ["promptpay.io", "promptpay.kasikornbank.com"], trustedDomains: ["promptpay.io", "kasikornbank.com"] },
  { id: "pix", displayName: "Pix", category: "brazil_latam", region: "Brazil", schemes: [], urlPatterns: ["pix.bcb.gov.br"], trustedDomains: ["bcb.gov.br"] },
  { id: "mercado_pago", displayName: "Mercado Pago", category: "brazil_latam", region: "LATAM", schemes: ["mercadopago://"], urlPatterns: ["mercadopago.com", "mpago.la"], trustedDomains: ["mercadopago.com", "mpago.la"] },
  { id: "picpay", displayName: "PicPay", category: "brazil_latam", region: "Brazil", schemes: ["picpay://"], urlPatterns: ["picpay.me/"], trustedDomains: ["picpay.me", "picpay.com"] },
  { id: "revolut", displayName: "Revolut", category: "europe", region: "Europe", schemes: ["revolut://"], urlPatterns: ["revolut.me/", "pay.revolut.com"], trustedDomains: ["revolut.com", "revolut.me"] },
  { id: "wise", displayName: "Wise (TransferWise)", category: "europe", region: "Global", schemes: ["wise://"], urlPatterns: ["wise.com/pay/", "transferwise.com"], trustedDomains: ["wise.com", "transferwise.com"] },
  { id: "twint", displayName: "TWINT", category: "europe", region: "Switzerland", schemes: ["twint://"], urlPatterns: ["app.twint.ch", "pay.twint.ch"], trustedDomains: ["twint.ch"] },
  { id: "swish_se", displayName: "Swish", category: "europe", region: "Sweden", schemes: ["swish://"], urlPatterns: ["swish.nu"], trustedDomains: ["swish.nu"] },
  { id: "bizum_es", displayName: "Bizum", category: "europe", region: "Spain", schemes: ["bizum://"], urlPatterns: ["bizum.es"], trustedDomains: ["bizum.es"] },
  { id: "satispay_it", displayName: "Satispay", category: "europe", region: "Italy", schemes: ["satispay://"], urlPatterns: ["satispay.com"], trustedDomains: ["satispay.com"] },
  { id: "blik_pl", displayName: "BLIK", category: "europe", region: "Poland", schemes: ["blik://"], urlPatterns: ["blik.pl"], trustedDomains: ["blik.pl"] },
  { id: "tikkie_nl", displayName: "Tikkie", category: "europe", region: "Netherlands", schemes: ["tikkie://"], urlPatterns: ["tikkie.me/"], trustedDomains: ["tikkie.me"] },
  { id: "mpesa", displayName: "M-Pesa", category: "africa", region: "Africa", schemes: ["mpesa://"], urlPatterns: ["m-pesa.com", "mpesa.safaricom.com", "safaricom.co.ke/mpesa"], trustedDomains: ["safaricom.co.ke", "m-pesa.com"] },
  { id: "stc_pay", displayName: "STC Pay", category: "middle_east", region: "Saudi Arabia", schemes: ["stcpay://"], urlPatterns: ["stcpay.com.sa"], trustedDomains: ["stcpay.com.sa"] },
  { id: "benefitpay", displayName: "BenefitPay", category: "middle_east", region: "Bahrain", schemes: ["benefitpay://"], urlPatterns: ["benefit.bh"], trustedDomains: ["benefit.bh"] },
  { id: "bitcoin", displayName: "Bitcoin (BTC)", category: "crypto", region: "Global", schemes: ["bitcoin:"], urlPatterns: [], trustedDomains: [] },
  { id: "ethereum", displayName: "Ethereum (ETH)", category: "crypto", region: "Global", schemes: ["ethereum:", "eth:"], urlPatterns: [], trustedDomains: [] },
  { id: "litecoin", displayName: "Litecoin (LTC)", category: "crypto", region: "Global", schemes: ["litecoin:"], urlPatterns: [], trustedDomains: [] },
  { id: "monero", displayName: "Monero (XMR)", category: "crypto", region: "Global", schemes: ["monero:"], urlPatterns: [], trustedDomains: [] },
  { id: "bitcoin_cash", displayName: "Bitcoin Cash (BCH)", category: "crypto", region: "Global", schemes: ["bitcoincash:"], urlPatterns: [], trustedDomains: [] },
  { id: "solana", displayName: "Solana (SOL)", category: "crypto", region: "Global", schemes: ["solana:"], urlPatterns: [], trustedDomains: [] },
  { id: "xrp", displayName: "XRP (Ripple)", category: "crypto", region: "Global", schemes: ["xrpl:", "ripple:", "xrp:"], urlPatterns: [], trustedDomains: [] },
  { id: "dogecoin", displayName: "Dogecoin (DOGE)", category: "crypto", region: "Global", schemes: ["dogecoin:"], urlPatterns: [], trustedDomains: [] },
  { id: "bnb", displayName: "BNB (Binance)", category: "crypto", region: "Global", schemes: ["bnb:", "binance:"], urlPatterns: [], trustedDomains: [] },
  { id: "tron", displayName: "TRON (TRX)", category: "crypto", region: "Global", schemes: ["tron:"], urlPatterns: [], trustedDomains: [] },
];

export const BANK_HANDLE_TO_APP: Record<string, { id: PaymentAppId; name: string }> = {
  "okhdfcbank": { id: "hdfc_bank", name: "HDFC Bank" },
  "hdfcbank": { id: "hdfc_bank", name: "HDFC Bank" },
  "payzapp": { id: "hdfc_bank", name: "HDFC Bank (PayZapp)" },
  "okaxis": { id: "axis_pay", name: "Axis Pay" },
  "axisbank": { id: "axis_pay", name: "Axis Pay" },
  "axl": { id: "axis_pay", name: "Axis Pay" },
  "oksbi": { id: "yono_sbi", name: "YONO SBI" },
  "sbi": { id: "yono_sbi", name: "YONO SBI" },
  "okicici": { id: "imobile_pay", name: "iMobile Pay (ICICI)" },
  "icici": { id: "imobile_pay", name: "iMobile Pay (ICICI)" },
  "ibl": { id: "imobile_pay", name: "iMobile Pay (ICICI)" },
  "ybl": { id: "phonepe", name: "PhonePe (Yes Bank)" },
  "superyes": { id: "phonepe", name: "PhonePe (Yes Bank)" },
  "paytm": { id: "paytm", name: "Paytm Payments Bank" },
  "kotak": { id: "kotak_pay", name: "Kotak Pay" },
  "kmbl": { id: "kotak_pay", name: "Kotak Pay" },
  "barodampay": { id: "bob_world", name: "BOB World Pay" },
  "bob": { id: "bob_world", name: "BOB World Pay" },
  "federal": { id: "fi_money", name: "Federal Bank / Fi" },
  "fbl": { id: "fi_money", name: "Fi Money (Federal Bank)" },
  "indus": { id: "indus_pay", name: "IndusPay (IndusInd)" },
  "idfcbank": { id: "idfcfirst", name: "IDFC FIRST Bank" },
  "idfcfirst": { id: "idfcfirst", name: "IDFC FIRST Bank" },
  "rbl": { id: "rbl_bank", name: "RBL MoBank" },
  "pnb": { id: "pnb_one", name: "PNB ONE" },
  "cnrb": { id: "canara_bank", name: "Canara Bank" },
  "ucobank": { id: "union_bank", name: "UCO Bank" },
  "mahb": { id: "union_bank", name: "Bank of Maharashtra" },
  "airtel": { id: "airtel_money", name: "Airtel Payments Bank" },
  "airtelpe": { id: "airtel_money", name: "Airtel Pay" },
  "jio": { id: "jiomoney", name: "JioMoney" },
  "abfspay": { id: "slice", name: "Aditya Birla Finance" },
  "sliceaxis": { id: "slice", name: "Slice" },
  "naviaxis": { id: "navi", name: "Navi" },
  "navi": { id: "navi", name: "Navi" },
  "amazonpay": { id: "amazon_pay", name: "Amazon Pay" },
  "apl": { id: "amazon_pay", name: "Amazon Pay" },
  "cred": { id: "cred", name: "CRED Pay" },
  "freecharge": { id: "freecharge", name: "FreeCharge" },
  "mobikwik": { id: "mobikwik", name: "MobiKwik" },
  "upi": { id: "upi", name: "UPI Payment" },
  "bhim": { id: "bhim", name: "BHIM" },
  "icicibank": { id: "imobile_pay", name: "iMobile Pay (ICICI)" },
  "hdfcbankjd": { id: "hdfc_bank", name: "HDFC Bank" },
  "postbank": { id: "upi", name: "India Post Payments Bank" },
  "timecosmos": { id: "upi", name: "Fino Payments Bank" },
  "jupiterpay": { id: "jupiter_money", name: "Jupiter Money" },
  "tapicici": { id: "imobile_pay", name: "ICICI Bank" },
  "yesbank": { id: "yes_pay", name: "Yes Pay (Yes Bank)" },
  "yesbankltd": { id: "yes_pay", name: "Yes Pay (Yes Bank)" },
  "groww": { id: "groww_pay", name: "Groww Pay" },
  "bajajpay": { id: "bajaj_pay", name: "Bajaj Pay" },
  "razorpay": { id: "razorpay", name: "Razorpay" },
  "juspay": { id: "juspay", name: "JusPay" },
};
