import React from "react";
import { View, Text, StyleSheet, Pressable, Platform } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import * as Clipboard from "expo-clipboard";
import * as Haptics from "@/lib/haptics";
import type { ParsedPaymentQr } from "@/lib/qr-analysis";
import { useTheme } from "@/contexts/ThemeContext";
import PaymentCard from "./PaymentCard";
import type { AppColors } from "@/constants/colors";
import { getQrTypeStyle } from "@/lib/config/qr-type-styles";

type GradientPair = readonly [string, string];

function parseWifi(content: string) {
  try {
    const ssid = content.match(/S:([^;]*)/)?.[1] ?? "";
    const password = content.match(/P:([^;]*)/)?.[1] ?? "";
    const security = content.match(/T:([^;]*)/)?.[1] ?? "WPA";
    const hidden = content.includes("H:true");
    if (!ssid) return null;
    return { ssid, password, security, hidden };
  } catch { return null; }
}

function parseContact(content: string) {
  const r = { name: "", phone: "", email: "", org: "", url: "", title: "", note: "" };
  if (content.startsWith("BEGIN:VCARD")) {
    // FN (Formatted Name) preferred; fall back to structured N field
    const fn = content.match(/^FN:(.+)$/m)?.[1]?.trim() ?? "";
    if (fn) {
      r.name = fn;
    } else {
      const nField = content.match(/^N:(.+)$/m)?.[1]?.trim() ?? "";
      // N field is Last;First;Middle;Prefix;Suffix — reassemble to "First Last"
      const [last = "", first = ""] = nField.split(";");
      r.name = [first.trim(), last.trim()].filter(Boolean).join(" ");
    }
    // TEL — strip type parameters like ;TYPE=CELL, ;TYPE=WORK
    r.phone = (content.match(/^TEL[^:\r\n]*:(.+)$/m)?.[1] ?? "").trim();
    // EMAIL — strip type parameters
    r.email = (content.match(/^EMAIL[^:\r\n]*:(.+)$/m)?.[1] ?? "").trim();
    r.org   = (content.match(/^ORG:(.+)$/m)?.[1] ?? "").trim().split(";")[0].trim();
    r.url   = (content.match(/^URL:(.+)$/m)?.[1] ?? "").trim();
    r.title = (content.match(/^TITLE:(.+)$/m)?.[1] ?? "").trim();
    r.note  = (content.match(/^NOTE:(.+)$/m)?.[1] ?? "").trim().slice(0, 120);
  } else if (content.toLowerCase().startsWith("mecard:")) {
    r.name  = content.match(/N:([^;]+)/)?.[1]?.trim() ?? "";
    r.phone = content.match(/TEL:([^;]+)/)?.[1]?.trim() ?? "";
    r.email = content.match(/EMAIL:([^;]+)/)?.[1]?.trim() ?? "";
  }
  return r;
}

function parseSms(content: string) {
  // Handle SMSTO:phone:message format (generated by the QR registry)
  const smsto = content.match(/^SMSTO:([^:]*):?(.*)?$/i);
  if (smsto) {
    return { to: smsto[1]?.trim() ?? "", body: smsto[2]?.trim() ?? "" };
  }
  // Handle sms:phone?body=message format
  try {
    const url = new URL(content);
    const to = url.pathname.replace(/^\//, "");
    const body = url.searchParams.get("body") ?? "";
    return { to, body };
  } catch { return { to: content.replace(/^sms[to]*:/i, "").split("?")[0], body: "" }; }
}

function parseWhatsApp(content: string) {
  try {
    const u = new URL(content.startsWith("http") ? content : `https://${content}`);
    const phone = u.pathname.replace(/^\//, "").replace(/\D/g, "");
    const text = u.searchParams.get("text") ?? "";
    return { phone: phone ? "+" + phone : content, text };
  } catch { return { phone: content, text: "" }; }
}

function parseEmail(content: string) {
  try {
    const bare = content.replace(/^mailto:/i, "");
    const [addr, qs = ""] = bare.split("?");
    const p = new URLSearchParams(qs);
    return { email: addr || "", subject: p.get("subject") ?? "", body: p.get("body") ?? "" };
  } catch { return { email: content, subject: "", body: "" }; }
}

function parsePhone(content: string) {
  return content.replace(/^(tel:|callto:|facetime:)/i, "").trim();
}

function parseEvent(content: string) {
  return {
    summary: content.match(/SUMMARY:([^\r\n]+)/)?.[1] ?? "",
    dtstart: content.match(/DTSTART[^:]*:([^\r\n]+)/)?.[1] ?? "",
    dtend: content.match(/DTEND[^:]*:([^\r\n]+)/)?.[1] ?? "",
    location: content.match(/LOCATION:([^\r\n]+)/)?.[1] ?? "",
    description: content.match(/DESCRIPTION:([^\r\n]+)/)?.[1] ?? "",
  };
}

function icalToDate(dt: string): Date | null {
  if (!dt) return null;
  try {
    const y = dt.slice(0, 4), mo = dt.slice(4, 6), d = dt.slice(6, 8);
    const h = dt.slice(9, 11) || "00", mi = dt.slice(11, 13) || "00";
    return new Date(`${y}-${mo}-${d}T${h}:${mi}:00`);
  } catch { return null; }
}

function formatEventDate(dt: string): string {
  if (!dt) return "";
  const date = icalToDate(dt);
  if (!date) return dt;
  return date.toLocaleDateString(undefined, { weekday: "long", year: "numeric", month: "long", day: "numeric" });
}

function formatEventTime(dt: string): string {
  if (!dt) return "";
  const date = icalToDate(dt);
  if (!date) return "";
  return date.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" });
}

function isEventPast(dtend: string, dtstart: string): boolean {
  const ref = dtend || dtstart;
  if (!ref) return false;
  const date = icalToDate(ref);
  return date ? date < new Date() : false;
}

function parseLocation(content: string) {
  const lower = content.toLowerCase();
  if (lower.startsWith("geo:")) {
    const afterGeo = content.slice(4);
    const [coordsPart, queryPart = ""] = afterGeo.split("?");
    const [lat = "", lon = ""] = coordsPart.split(",");
    const label = new URLSearchParams(queryPart).get("q") || "";
    return { lat: lat.trim(), lon: lon.trim(), label: label ? decodeURIComponent(label) : "" };
  }
  if (lower.includes("maps.google.com") || lower.includes("goo.gl/maps")) {
    try {
      const u = new URL(content);
      const q = u.searchParams.get("q") || "";
      return { lat: "", lon: "", label: q ? decodeURIComponent(q) : content };
    } catch {}
  }
  return { lat: "", lon: "", label: content };
}

function parseCrypto(content: string) {
  const m = content.match(/^(bitcoin|ethereum|litecoin|solana):([^?]+)(\?(.*))?$/i);
  if (m) {
    const coin = m[1].charAt(0).toUpperCase() + m[1].slice(1);
    const address = m[2].trim();
    const amount = new URLSearchParams(m[4] || "").get("amount") || "";
    return { coin, address, amount };
  }
  return { coin: "", address: content, amount: "" };
}

function extractBasicPaymentInfo(content: string) {
  try {
    return {
      vpa: content.match(/pa=([^&\s]+)/i)?.[1] ? decodeURIComponent(content.match(/pa=([^&\s]+)/i)![1]) : undefined,
      name: content.match(/pn=([^&\s]+)/i)?.[1] ? decodeURIComponent(content.match(/pn=([^&\s]+)/i)![1]) : undefined,
      amount: content.match(/(?:\bam|amount)=([^&\s]+)/i)?.[1] ? decodeURIComponent(content.match(/(?:\bam|amount)=([^&\s]+)/i)![1]) : undefined,
      currency: content.match(/cu=([^&\s]+)/i)?.[1] ? decodeURIComponent(content.match(/cu=([^&\s]+)/i)![1]) : undefined,
    };
  } catch { return {}; }
}

// ── URL type field extractor ────────────────────────────────────────────────
// For URL-based template types, pull meaningful fields back out of the URL
// so ContentCard can show them as structured InfoRows instead of bare links.
type UrlField = { label: string; value: string; icon: keyof typeof Ionicons.glyphMap };

function extractUrlDisplayFields(contentType: string, content: string): UrlField[] {
  const fields: UrlField[] = [];
  try {
    switch (contentType) {
      case "instagram": {
        const m = content.match(/instagram\.com\/([^/?#\s]+)/);
        if (m?.[1] && m[1] !== "p" && m[1] !== "reel") fields.push({ label: "Profile", value: `@${m[1]}`, icon: "person-outline" });
        break;
      }
      case "twitter": {
        const m = content.match(/(?:twitter|x)\.com\/([^/?#\s]+)/);
        if (m?.[1] && !["i", "intent", "home", "explore"].includes(m[1])) fields.push({ label: "Username", value: `@${m[1]}`, icon: "person-outline" });
        break;
      }
      case "tiktok": {
        const m = content.match(/tiktok\.com\/@([^/?#\s]+)/);
        if (m?.[1]) fields.push({ label: "Username", value: `@${m[1]}`, icon: "person-outline" });
        break;
      }
      case "snapchat": {
        const m = content.match(/snapchat\.com\/add\/([^/?#\s]+)/);
        if (m?.[1]) fields.push({ label: "Username", value: m[1], icon: "person-outline" });
        break;
      }
      case "youtube": {
        const channel = content.match(/youtube\.com\/@([^/?#\s]+)/)?.[1] ?? content.match(/youtube\.com\/channel\/([^/?#\s]+)/)?.[1] ?? content.match(/youtube\.com\/c\/([^/?#\s]+)/)?.[1];
        const video = content.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&/?#\s]+)/)?.[1];
        if (channel) fields.push({ label: "Channel", value: `@${channel}`, icon: "play-circle-outline" });
        if (video)   fields.push({ label: "Video", value: video, icon: "play-outline" });
        break;
      }
      case "spotify": {
        const track    = content.match(/spotify\.com\/track\/([^/?#\s]+)/)?.[1];
        const album    = content.match(/spotify\.com\/album\/([^/?#\s]+)/)?.[1];
        const playlist = content.match(/spotify\.com\/playlist\/([^/?#\s]+)/)?.[1];
        const artist   = content.match(/spotify\.com\/artist\/([^/?#\s]+)/)?.[1];
        if (track)    fields.push({ label: "Track", value: track, icon: "musical-note-outline" });
        else if (album)    fields.push({ label: "Album", value: album, icon: "disc-outline" });
        else if (playlist) fields.push({ label: "Playlist", value: playlist, icon: "musical-notes-outline" });
        else if (artist)   fields.push({ label: "Artist", value: artist, icon: "person-outline" });
        break;
      }
      case "linkedin": {
        const m = content.match(/linkedin\.com\/(?:in|company|school)\/([^/?#\s]+)/);
        if (m?.[1]) fields.push({ label: "Profile", value: m[1], icon: "person-outline" });
        break;
      }
      case "telegram": {
        const m = content.match(/t\.me\/([^/?#\s]+)/);
        if (m?.[1]) fields.push({ label: "Username", value: `@${m[1]}`, icon: "paper-plane-outline" });
        break;
      }
      case "discord": {
        const m = content.match(/discord\.(?:gg|com\/invite)\/([^/?#\s]+)/);
        if (m?.[1]) fields.push({ label: "Invite", value: m[1], icon: "link-outline" });
        break;
      }
      case "facebook": {
        const u = new URL(content.startsWith("http") ? content : `https://${content}`);
        const path = u.pathname.replace(/^\/|\/$/g, "");
        if (path && !["pages", "groups", "events", "login"].includes(path.split("/")[0]))
          fields.push({ label: "Page", value: path, icon: "person-outline" });
        break;
      }
      case "paypal": {
        const username = content.match(/paypal\.me\/([^/?#\s/]+)/)?.[1];
        const amount   = content.match(/paypal\.me\/[^/]+\/([^/?#\s]+)/)?.[1];
        if (username) fields.push({ label: "Username", value: username, icon: "person-outline" });
        if (amount)   fields.push({ label: "Amount", value: amount, icon: "cash-outline" });
        break;
      }
      case "venmo": {
        const u = new URL(content.startsWith("http") ? content : `https://${content}`);
        const username = u.pathname.replace(/^\/@?|\/$/g, "") || u.searchParams.get("user") || "";
        const amount   = u.searchParams.get("amount") ?? "";
        const note     = u.searchParams.get("note") ?? "";
        if (username) fields.push({ label: "Username", value: `@${username}`, icon: "person-outline" });
        if (amount)   fields.push({ label: "Amount", value: amount, icon: "cash-outline" });
        if (note)     fields.push({ label: "Note", value: note, icon: "document-text-outline" });
        break;
      }
      case "zoom": {
        const meetingId = content.includes("zoom.us/j/") ? content.split("/j/")[1]?.split("?")[0] ?? "" : "";
        let pwd = "";
        try { pwd = new URL(content).searchParams.get("pwd") ?? ""; } catch {}
        if (meetingId) fields.push({ label: "Meeting ID", value: meetingId, icon: "videocam-outline" });
        if (pwd)       fields.push({ label: "Passcode", value: pwd, icon: "key-outline" });
        break;
      }
      case "calendly": {
        const u = new URL(content.startsWith("http") ? content : `https://${content}`);
        const parts = u.pathname.replace(/^\/|\/$/g, "").split("/").filter(Boolean);
        if (parts[0]) fields.push({ label: "Username", value: parts[0], icon: "person-outline" });
        if (parts[1]) fields.push({ label: "Event", value: parts[1].replace(/-/g, " "), icon: "calendar-outline" });
        break;
      }
      case "razorpay":
      case "donation":
      case "reviewpage":
      case "menucatalogue": {
        try {
          const u = new URL(content.startsWith("http") ? content : `https://${content}`);
          fields.push({ label: "Link", value: u.hostname.replace(/^www\./, "") + u.pathname.replace(/\/$/, ""), icon: "link-outline" });
        } catch {}
        break;
      }
      default:
        break;
    }
  } catch {}
  return fields;
}

interface Props {
  content: string;
  contentType: string;
  parsedPayment: ParsedPaymentQr | null;
  isDeactivated: boolean;
  onOpenContent: () => void;
  hideOpenAction?: boolean;
  templateKey?: string;
}

const EXPAND_THRESHOLD = 120;

const ContentCard = React.memo(function ContentCard({ content, contentType, parsedPayment, isDeactivated, onOpenContent, hideOpenAction, templateKey }: Props) {
  const { colors, isDark } = useTheme();
  const [copied, setCopied] = React.useState(false);
  const [contentExpanded, setContentExpanded] = React.useState(false);

  const isLongContent = content.length > EXPAND_THRESHOLD || content.includes("\n");
  const cfg = getQrTypeStyle(contentType, templateKey);
  const hasOpenAction = !isDeactivated && !hideOpenAction && effectiveType !== "text" && effectiveType !== "product";

  async function handleCopy() {
    await Clipboard.setStringAsync(content);
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    if (Platform.OS !== "android") {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  // effectiveType: use templateKey whenever it carries a specific type (not a
  // generic alias). This ensures Business QR templates (reviewpage, menucatalogue,
  // etc.) and structured types (wifi, contact, …) stored only as templateKey are
  // rendered correctly even when contentType is the broad "url" or "text".
  const GENERIC_TYPES = new Set(["url", "text", "biolink"]);
  const effectiveType = (templateKey && !GENERIC_TYPES.has(templateKey)) ? templateKey : contentType;

  const URL_LIKE_TYPES = new Set(["url", "instagram", "twitter", "youtube", "linkedin", "telegram", "facebook", "spotify", "discord", "tiktok", "zoom", "calendly", "appdownload", "app", "social", "media", "paypal", "venmo", "mobilepay", "reviewpage", "menucatalogue", "donation", "razorpay", "snapchat"]);
  const isUrlLike = URL_LIKE_TYPES.has(effectiveType) || URL_LIKE_TYPES.has(contentType);

  const wifi = effectiveType === "wifi" ? parseWifi(content) : null;
  const contact = effectiveType === "contact" ? parseContact(content) : null;
  const smsData = effectiveType === "sms" ? parseSms(content) : null;
  const eventData = (effectiveType === "event" || effectiveType === "calendar") ? parseEvent(content) : null;
  const whatsappData = effectiveType === "whatsapp" ? parseWhatsApp(content) : null;
  const emailData = effectiveType === "email" ? parseEmail(content) : null;
  const phoneStr = effectiveType === "phone" ? parsePhone(content) : null;
  const locationData = effectiveType === "location" ? parseLocation(content) : null;
  const cryptoData = effectiveType === "crypto" ? parseCrypto(content) : null;
  const eventOver = eventData ? isEventPast(eventData.dtend, eventData.dtstart) : false;

  const smartActionLabel = React.useMemo((): string => {
    if ((effectiveType === "contact" || effectiveType === "mecard") && contact) {
      if (contact.phone) return "Call Now";
      if (contact.email) return "Send Email";
    }
    return cfg.openLabel;
  }, [effectiveType, contact, cfg.openLabel]);

  const smartActionIcon = React.useMemo((): keyof typeof Ionicons.glyphMap => {
    if ((effectiveType === "contact" || effectiveType === "mecard") && contact) {
      if (contact.phone) return "call-outline";
      if (contact.email) return "mail-outline";
    }
    return "open-outline";
  }, [effectiveType, contact]);
  const isPaymentType = effectiveType === "payment" || effectiveType === "upi" || effectiveType === "scantopay" || effectiveType === "paymentlink";
  const basicPayment = (isPaymentType && !parsedPayment) ? extractBasicPaymentInfo(content) : null;
  const isEmvContent = content.startsWith("000201") || content.startsWith("00020");

  if (effectiveType === "encrypted") {
    const preview = content.length > 40 ? content.slice(0, 40) + "…" : content;
    const isBase64 = /^[A-Za-z0-9+/]{20,}={0,2}$/.test(content.trim());
    const isHex = /^[0-9a-fA-F]{40,}$/.test(content.trim());
    const dataHint = isBase64 ? "Base64-encoded" : isHex ? "Hex-encoded" : "Proprietary";
    return (
      <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.warning + "50" }]}>
        <LinearGradient colors={[colors.warning + (isDark ? "20" : "10"), "transparent"]} style={StyleSheet.absoluteFill} />
        {/* Header */}
        <View style={styles.cardHeader}>
          <LinearGradient colors={[colors.warning, colors.warningShade ?? colors.warning]} style={styles.cardIcon} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }}>
            <Ionicons name="key-outline" size={22} color="#fff" />
          </LinearGradient>
          <View style={{ flex: 1 }}>
            <Text style={[styles.cardTitle, { color: colors.text }]}>Encrypted Data</Text>
            <Text style={[styles.cardSub, { color: colors.textMuted }]}>{dataHint} · {content.length} chars</Text>
          </View>
          <Pressable onPress={handleCopy} style={({ pressed }) => [styles.copyBtn, { backgroundColor: copied ? colors.safe + "18" : isDark ? colors.surfaceLight : colors.background, borderColor: copied ? colors.safe : colors.surfaceBorder, opacity: pressed ? 0.75 : 1 }]}>
            <Ionicons name={copied ? "checkmark-circle" : "copy-outline"} size={14} color={copied ? colors.safe : colors.textMuted} />
            <Text style={[styles.copiedText, { color: copied ? colors.safe : colors.textMuted }]}>{copied ? "Copied!" : "Copy"}</Text>
          </Pressable>
        </View>
        <View style={[styles.infoChipRow, { backgroundColor: colors.warning + "12", borderColor: colors.warning + "30" }]}>
          <Ionicons name="information-circle-outline" size={13} color={colors.warning} />
          <Text style={[styles.infoChipText, { color: colors.warning }]}>
            Proprietary or government-issued data — requires issuer's key to decode.
          </Text>
        </View>
        <View style={[styles.rawBox, { backgroundColor: isDark ? colors.surfaceLight : colors.background, borderColor: colors.surfaceBorder }]}>
          <Text style={[styles.rawText, { color: colors.textMuted }]} selectable numberOfLines={2}>{preview}</Text>
        </View>
      </View>
    );
  }

  if (effectiveType === "payment" || effectiveType === "upi" || effectiveType === "scantopay" || effectiveType === "paymentlink") {
    const paymentData: ParsedPaymentQr = parsedPayment ?? (isEmvContent ? {
      app: "emv_generic", appDisplayName: "Bank Merchant QR", appCategory: "emv",
      region: "Regional", recipientId: "", rawContent: content, isAmountPreFilled: false,
    } : {
      app: "upi", appDisplayName: "UPI Payment", appCategory: "upi_india", region: "India",
      recipientId: basicPayment?.vpa || "", recipientName: basicPayment?.name,
      amount: basicPayment?.amount, currency: basicPayment?.currency || "INR",
      rawContent: content, isAmountPreFilled: !!basicPayment?.amount, vpa: basicPayment?.vpa,
    });
    return <View><PaymentCard parsedPayment={paymentData} isDeactivated={isDeactivated} onOpenContent={onOpenContent} /></View>;
  }

  const urlFields = isUrlLike ? extractUrlDisplayFields(effectiveType, content) : [];

  const accentColor = cfg.gradient[0];
  const accentAlpha = isDark ? "22" : "12";

  return (
    <View style={[styles.card, { backgroundColor: colors.surface, borderColor: accentColor + "45" }]}>
      <LinearGradient
        colors={[accentColor + (isDark ? "18" : "0C"), "transparent"]}
        style={StyleSheet.absoluteFill}
      />

      {/* Card header — icon + type label + copy */}
      <View style={styles.cardHeader}>
        <LinearGradient colors={[...cfg.gradient]} style={styles.cardIcon} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }}>
          <Ionicons name={cfg.icon as keyof typeof Ionicons.glyphMap} size={22} color="#fff" />
        </LinearGradient>
        <View style={{ flex: 1 }}>
          <Text style={[styles.cardTitle, { color: colors.text }]}>{cfg.label}</Text>
          {isUrlLike && (
            <Text style={[styles.cardSub, { color: colors.textMuted }]} numberOfLines={1}>
              {cfg.extractDisplayValue
                ? cfg.extractDisplayValue(content)
                : (() => {
                    try {
                      const parsed = new URL(content.startsWith("http") ? content : `https://${content}`);
                      const h = parsed.hostname.toLowerCase();
                      const isPrivate = /^(localhost|127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(h);
                      if (isPrivate || parsed.pathname.startsWith("/guard/")) return "Smart Redirect";
                      return h.replace(/^www\./, "");
                    } catch { return ""; }
                  })()
              }
            </Text>
          )}
        </View>
        <Pressable
          onPress={handleCopy}
          style={({ pressed }) => [styles.copyBtn, {
            backgroundColor: copied ? colors.safe + "18" : isDark ? colors.surfaceLight : colors.background,
            borderColor: copied ? colors.safe : colors.surfaceBorder,
            opacity: pressed ? 0.75 : 1,
          }]}
        >
          <Ionicons name={copied ? "checkmark-circle" : "copy-outline"} size={14} color={copied ? colors.safe : colors.textMuted} />
          <Text style={[styles.copiedText, { color: copied ? colors.safe : colors.textMuted }]}>{copied ? "Copied!" : "Copy"}</Text>
        </Pressable>
      </View>

      {/* Structured fields extracted from URL-like types (Instagram, YouTube, etc.) */}
      {isUrlLike && urlFields.length > 0 && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          {urlFields.map((f, i) => (
            <React.Fragment key={f.label}>
              {i > 0 && <Divider colors={colors} />}
              <InfoRow label={f.label} value={f.value} icon={f.icon} accentColor={accentColor} colors={colors} selectable />
            </React.Fragment>
          ))}
        </View>
      )}

      {/* Plain text content — only for types that have no structured parser */}
      {!isUrlLike && !["wifi", "sms", "event", "calendar", "whatsapp", "email", "phone", "location", "crypto", "contact"].includes(effectiveType) && (
        <View style={[styles.rawBox, { backgroundColor: isDark ? colors.surfaceLight : colors.background, borderColor: colors.surfaceBorder }]}>
          <Text style={[styles.rawText, { color: colors.text }]} selectable numberOfLines={contentExpanded ? undefined : 4}>
            {content}
          </Text>
          {isLongContent && (
            <Pressable onPress={() => setContentExpanded(v => !v)}>
              <Text style={[styles.expandBtnText, { color: accentColor }]}>{contentExpanded ? "Show less" : "Show more"}</Text>
            </Pressable>
          )}
        </View>
      )}

      {/* Structured info cards */}
      {wifi && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          <InfoRow label="Network" value={wifi.ssid} icon="wifi-outline" accentColor={accentColor} colors={colors} />
          <Divider colors={colors} />
          <InfoRow label="Security" value={wifi.security} icon="lock-closed-outline" accentColor={accentColor} colors={colors} />
          {wifi.password ? <><Divider colors={colors} /><InfoRow label="Password" value={wifi.password} icon="key-outline" accentColor={accentColor} colors={colors} selectable /></> : null}
          {wifi.hidden ? <><Divider colors={colors} /><InfoRow label="Hidden" value="Yes" icon="eye-off-outline" accentColor={accentColor} colors={colors} /></> : null}
        </View>
      )}
      {contact && (contact.name || contact.phone || contact.email) && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          {contact.name  ? <InfoRow label="Name"    value={contact.name}  icon="person-outline"   accentColor={accentColor} colors={colors} /> : null}
          {contact.title ? <><Divider colors={colors} /><InfoRow label="Title"   value={contact.title} icon="briefcase-outline" accentColor={accentColor} colors={colors} /></> : null}
          {contact.org   ? <><Divider colors={colors} /><InfoRow label="Company" value={contact.org}   icon="business-outline" accentColor={accentColor} colors={colors} /></> : null}
          {contact.phone ? <><Divider colors={colors} /><InfoRow label="Phone"   value={contact.phone} icon="call-outline"      accentColor={accentColor} colors={colors} selectable /></> : null}
          {contact.email ? <><Divider colors={colors} /><InfoRow label="Email"   value={contact.email} icon="mail-outline"      accentColor={accentColor} colors={colors} selectable /></> : null}
          {contact.url   ? <><Divider colors={colors} /><InfoRow label="Website" value={contact.url}   icon="link-outline"      accentColor={accentColor} colors={colors} selectable /></> : null}
          {contact.note  ? <><Divider colors={colors} /><InfoRow label="Note"    value={contact.note}  icon="document-text-outline" accentColor={accentColor} colors={colors} /></> : null}
        </View>
      )}
      {smsData && (smsData.to || smsData.body) && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          {smsData.to ? <InfoRow label="To" value={smsData.to} icon="person-outline" accentColor={accentColor} colors={colors} /> : null}
          {smsData.body ? <><Divider colors={colors} /><InfoRow label="Message" value={smsData.body} icon="chatbubble-outline" accentColor={accentColor} colors={colors} /></> : null}
        </View>
      )}
      {whatsappData && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          {whatsappData.phone ? <InfoRow label="Number" value={whatsappData.phone} icon="logo-whatsapp" accentColor={accentColor} colors={colors} selectable /> : null}
          {whatsappData.text ? <><Divider colors={colors} /><InfoRow label="Message" value={whatsappData.text} icon="chatbubble-outline" accentColor={accentColor} colors={colors} selectable /></> : null}
        </View>
      )}
      {emailData && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          {emailData.email ? <InfoRow label="Email" value={emailData.email} icon="mail-outline" accentColor={accentColor} colors={colors} selectable /> : null}
          {emailData.subject ? <><Divider colors={colors} /><InfoRow label="Subject" value={emailData.subject} icon="text-outline" accentColor={accentColor} colors={colors} selectable /></> : null}
          {emailData.body ? <><Divider colors={colors} /><InfoRow label="Body" value={emailData.body} icon="document-text-outline" accentColor={accentColor} colors={colors} selectable /></> : null}
        </View>
      )}
      {phoneStr && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          <InfoRow label="Phone" value={phoneStr} icon="call-outline" accentColor={accentColor} colors={colors} selectable />
        </View>
      )}
      {locationData && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          {locationData.label ? <InfoRow label="Place" value={locationData.label} icon="location-outline" accentColor={accentColor} colors={colors} /> : null}
          {locationData.lat ? <><Divider colors={colors} /><InfoRow label="Lat" value={locationData.lat} icon="navigate-outline" accentColor={accentColor} colors={colors} selectable /></> : null}
          {locationData.lon ? <><Divider colors={colors} /><InfoRow label="Lon" value={locationData.lon} icon="navigate-outline" accentColor={accentColor} colors={colors} selectable /></> : null}
        </View>
      )}
      {cryptoData && (
        <View style={[styles.infoGrid, { backgroundColor: accentColor + accentAlpha, borderColor: accentColor + "30" }]}>
          {cryptoData.coin ? <InfoRow label="Coin" value={cryptoData.coin} icon="logo-bitcoin" accentColor={accentColor} colors={colors} /> : null}
          <><Divider colors={colors} /><InfoRow label="Address" value={cryptoData.address} icon="copy-outline" accentColor={accentColor} colors={colors} selectable /></>
          {cryptoData.amount ? <><Divider colors={colors} /><InfoRow label="Amount" value={cryptoData.amount} icon="cash-outline" accentColor={accentColor} colors={colors} /></> : null}
        </View>
      )}
      {eventData && (
        <View style={{ gap: 10 }}>
          {eventOver && (
            <View style={[styles.eventOverBanner, { backgroundColor: colors.danger + "15", borderColor: colors.danger + "40" }]}>
              <Ionicons name="time-outline" size={15} color={colors.danger} />
              <Text style={[styles.eventOverText, { color: colors.danger }]}>This event has already ended</Text>
            </View>
          )}
          <View style={[styles.eventCard, { backgroundColor: isDark ? colors.surfaceLight : colors.background, borderColor: colors.surfaceBorder }]}>
            {eventData.summary ? (
              <Text style={[styles.eventTitle, { color: colors.text }]}>{eventData.summary}</Text>
            ) : null}
            {eventData.dtstart ? (
              <View style={styles.eventDetailRow}>
                <View style={[styles.eventDetailIcon, { backgroundColor: cfg.gradient[0] + "18" }]}>
                  <Ionicons name="calendar-outline" size={14} color={cfg.gradient[0]} />
                </View>
                <Text style={[styles.eventDetailText, { color: colors.textSecondary }]}>
                  {formatEventDate(eventData.dtstart)}
                </Text>
              </View>
            ) : null}
            {(eventData.dtstart || eventData.dtend) ? (
              <View style={styles.eventDetailRow}>
                <View style={[styles.eventDetailIcon, { backgroundColor: cfg.gradient[0] + "18" }]}>
                  <Ionicons name="time-outline" size={14} color={cfg.gradient[0]} />
                </View>
                <Text style={[styles.eventDetailText, { color: colors.textSecondary }]}>
                  {eventData.dtstart ? formatEventTime(eventData.dtstart) : ""}
                  {eventData.dtend && eventData.dtstart !== eventData.dtend
                    ? ` – ${formatEventTime(eventData.dtend)}`
                    : ""}
                </Text>
              </View>
            ) : null}
            {eventData.location ? (
              <View style={styles.eventDetailRow}>
                <View style={[styles.eventDetailIcon, { backgroundColor: cfg.gradient[0] + "18" }]}>
                  <Ionicons name="location-outline" size={14} color={cfg.gradient[0]} />
                </View>
                <Text style={[styles.eventDetailText, { color: colors.textSecondary }]} numberOfLines={2}>
                  {eventData.location}
                </Text>
              </View>
            ) : null}
            {eventData.description ? (
              <View style={styles.eventDetailRow}>
                <View style={[styles.eventDetailIcon, { backgroundColor: cfg.gradient[0] + "18" }]}>
                  <Ionicons name="information-circle-outline" size={14} color={cfg.gradient[0]} />
                </View>
                <Text style={[styles.eventDetailText, { color: colors.textSecondary }]} numberOfLines={3}>
                  {eventData.description}
                </Text>
              </View>
            ) : null}
          </View>
        </View>
      )}

      {/* Open action */}
      {hasOpenAction && (
        <Pressable onPress={onOpenContent} style={({ pressed }) => [{ opacity: pressed ? 0.85 : 1 }]}>
          <LinearGradient colors={[...cfg.gradient]} style={styles.openBtn} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}>
            <Ionicons name={smartActionIcon} size={14} color="#fff" />
            <Text style={styles.openBtnText}>{smartActionLabel}</Text>
          </LinearGradient>
        </Pressable>
      )}
    </View>
  );
});

function InfoRow({ label, value, selectable, icon, accentColor, colors }: { label: string; value: string; selectable?: boolean; icon: keyof typeof Ionicons.glyphMap; accentColor: string; colors: any }) {
  return (
    <View style={styles.infoRow}>
      <View style={[styles.infoIconWrap, { backgroundColor: accentColor + "20" }]}>
        <Ionicons name={icon} size={13} color={accentColor} />
      </View>
      <Text style={[styles.infoLabel, { color: colors.textSecondary }]}>{label}</Text>
      <Text style={[styles.infoValue, { color: colors.text }]} selectable={selectable} numberOfLines={2}>{value}</Text>
    </View>
  );
}

function Divider({ colors }: { colors: any }) {
  return <View style={[styles.divider, { backgroundColor: colors.surfaceBorder }]} />;
}

export default ContentCard;

const styles = StyleSheet.create({
  card: {
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    overflow: "hidden",
    gap: 12,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  cardIcon: {
    width: 48,
    height: 48,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  cardTitle: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
  },
  cardSub: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  copyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    height: 28,
    paddingHorizontal: 9,
    borderRadius: 8,
    borderWidth: 1,
  },
  copiedText: { fontSize: 11, fontFamily: "Inter_600SemiBold" },
  rawBox: {
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    gap: 6,
  },
  rawText: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  expandBtnText: { fontSize: 12, fontFamily: "Inter_600SemiBold", marginTop: 4 },
  infoGrid: {
    borderRadius: 14,
    padding: 12,
    gap: 0,
    borderWidth: 1,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 9,
  },
  infoIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  infoLabel: { fontSize: 12, fontFamily: "Inter_500Medium", width: 68 },
  infoValue: { fontSize: 13, fontFamily: "Inter_600SemiBold", flex: 1, textAlign: "right" },
  divider: { height: 1, marginHorizontal: -2 },
  infoChipRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderWidth: 1,
  },
  infoChipText: { fontSize: 12, fontFamily: "Inter_400Regular", flex: 1, lineHeight: 17 },
  openBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  openBtnText: { fontSize: 14, fontFamily: "Inter_700Bold", color: "#fff" },
  eventOverBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
  },
  eventOverText: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  eventCard: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    gap: 12,
  },
  eventTitle: {
    fontSize: 17,
    fontFamily: "Inter_700Bold",
    lineHeight: 24,
  },
  eventDetailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  eventDetailIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: 1,
  },
  eventDetailText: {
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    flex: 1,
    lineHeight: 20,
  },
});
