import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.dark.background },
  centered: { flex: 1, alignItems: "center", justifyContent: "center" },
  emptyText: { fontSize: 15, fontFamily: "Inter_500Medium", color: Colors.dark.textMuted },
  navBar: {
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    paddingHorizontal: 16, paddingVertical: 13,
    borderBottomWidth: 1, borderBottomColor: Colors.dark.surfaceBorder,
  },
  backBtn: {
    width: 40, height: 40, borderRadius: 20,
    backgroundColor: Colors.dark.surface, borderWidth: 1, borderColor: Colors.dark.surfaceBorder,
    alignItems: "center", justifyContent: "center",
  },
  navTitle: { fontSize: 18, fontFamily: "Inter_700Bold", color: Colors.dark.text, flex: 1, textAlign: "center" },
  scroll: { padding: 16, gap: 14 },
  previewCard: {
    backgroundColor: Colors.dark.surface, borderRadius: 20,
    borderWidth: 1, borderColor: Colors.dark.surfaceBorder,
    alignItems: "center", paddingVertical: 24, paddingHorizontal: 20,
  },
  qrBg: {
    borderRadius: 16, padding: 12, position: "relative",
    shadowColor: "#000", shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25, shadowRadius: 8, elevation: 6,
  },
  cornerLogoWrapper: { position: "absolute", width: 36, height: 36 },
  cornerLogoImg: { width: 36, height: 36, borderRadius: 8 },
  uuidRow: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 14 },
  uuidText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: Colors.dark.safe, letterSpacing: 0.5 },
  metaCard: {
    backgroundColor: Colors.dark.surface, borderRadius: 16,
    borderWidth: 1, borderColor: Colors.dark.surfaceBorder, padding: 16,
  },
  sectionLabel: {
    fontSize: 11, fontFamily: "Inter_600SemiBold", color: Colors.dark.textMuted,
    textTransform: "uppercase", letterSpacing: 0.8, marginBottom: 12,
  },
  metaIconWrap: {
    width: 34, height: 34, borderRadius: 10,
    backgroundColor: Colors.dark.primaryDim, alignItems: "center", justifyContent: "center",
  },
  metaLabel: { fontSize: 10, fontFamily: "Inter_400Regular", color: Colors.dark.textMuted, marginBottom: 2 },
  metaValue: { fontSize: 15, fontFamily: "Inter_700Bold", color: Colors.dark.text },
  divider: { height: 1, backgroundColor: Colors.dark.surfaceBorder, marginVertical: 12 },
  metaContentRow: { marginBottom: 10 },
  lockedRow: { flexDirection: "row", alignItems: "flex-start", gap: 5, marginTop: 3 },
  metaContentValue: { fontSize: 13, fontFamily: "Inter_400Regular", color: Colors.dark.textSecondary, flex: 1 },
  copyBtn: {
    flexDirection: "row", alignItems: "center", gap: 6,
    backgroundColor: Colors.dark.surfaceLight, borderRadius: 10, borderWidth: 1, borderColor: Colors.dark.surfaceBorder,
    paddingHorizontal: 10, paddingVertical: 6, alignSelf: "flex-start", marginTop: 8,
  },
  designHeader: {
    backgroundColor: Colors.dark.surface, borderRadius: 16, borderWidth: 1,
    borderColor: Colors.dark.surfaceBorder, padding: 16,
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
  },
  designHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  designHeaderText: { fontSize: 15, fontFamily: "Inter_600SemiBold", color: Colors.dark.text },
  dirtyDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: Colors.dark.warning, marginLeft: 4 },
  designPanel: {
    backgroundColor: Colors.dark.surface, borderRadius: 16, borderWidth: 1,
    borderColor: Colors.dark.surfaceBorder, padding: 16,
    marginTop: -8, borderTopLeftRadius: 0, borderTopRightRadius: 0,
  },
  designLabel: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: Colors.dark.textSecondary, marginBottom: 8 },
  swatchRow: { flexDirection: "row", gap: 10 },
  swatch: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "transparent" },
  swatchSelected: { borderColor: Colors.dark.primary },
  logoRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 4 },
  logoPickerBtn: {
    flexDirection: "row", alignItems: "center", gap: 10,
    backgroundColor: Colors.dark.surfaceLight, borderRadius: 12, padding: 10,
    borderWidth: 1, borderColor: Colors.dark.surfaceBorder,
  },
  logoThumb: { width: 32, height: 32, borderRadius: 8 },
  logoPickerLabel: { fontSize: 13, fontFamily: "Inter_500Medium", color: Colors.dark.text },
  positionRow: { flexDirection: "row", gap: 8 },
  positionBtn: {
    paddingVertical: 7, paddingHorizontal: 14, borderRadius: 20,
    backgroundColor: Colors.dark.surfaceLight, borderWidth: 1, borderColor: Colors.dark.surfaceBorder,
  },
  positionBtnActive: { backgroundColor: Colors.dark.primaryDim, borderColor: Colors.dark.primary },
  positionBtnText: { fontSize: 12, fontFamily: "Inter_500Medium", color: Colors.dark.textMuted },
  positionBtnTextActive: { color: Colors.dark.primary },
  saveDesignBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    gap: 8, backgroundColor: Colors.dark.primary, borderRadius: 14, paddingVertical: 13,
  },
  saveDesignBtnText: { fontSize: 15, fontFamily: "Inter_700Bold", color: "#000" },
  commentsHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 4 },
  commentCountBadge: {
    backgroundColor: Colors.dark.primaryDim, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2,
  },
  commentCountText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: Colors.dark.primary },
  emptyComments: { alignItems: "center", paddingVertical: 36, gap: 8 },
  emptyCommentsText: { fontSize: 15, fontFamily: "Inter_600SemiBold", color: Colors.dark.textSecondary },
  emptyCommentsSub: { fontSize: 12, fontFamily: "Inter_400Regular", color: Colors.dark.textMuted },
  commentsList: { gap: 4 },
  commentBlock: {
    backgroundColor: Colors.dark.surface, borderRadius: 14,
    borderWidth: 1, borderColor: Colors.dark.surfaceBorder, overflow: "hidden",
  },
  repliesContainer: { borderTopWidth: 1, borderTopColor: Colors.dark.surfaceBorder, paddingTop: 4 },
  toggleRepliesBtn: { flexDirection: "row", alignItems: "center", gap: 5, paddingVertical: 8, paddingHorizontal: 12 },
  toggleRepliesText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: Colors.dark.primary },
  replyRow: { flexDirection: "row", paddingHorizontal: 10, paddingBottom: 4 },
  replyLine: { width: 2, backgroundColor: Colors.dark.primaryDim, borderRadius: 1, marginRight: 8, marginLeft: 8 },
  inputBar: {
    backgroundColor: Colors.dark.surface, borderTopWidth: 1,
    borderTopColor: Colors.dark.surfaceBorder, paddingHorizontal: 14, paddingTop: 10,
  },
  replyBanner: {
    flexDirection: "row", alignItems: "center", gap: 6,
    backgroundColor: Colors.dark.primaryDim, borderRadius: 10,
    paddingHorizontal: 10, paddingVertical: 6, marginBottom: 8,
  },
  replyBannerText: { fontSize: 12, fontFamily: "Inter_500Medium", color: Colors.dark.textMuted, flex: 1 },
  inputRow: { flexDirection: "row", alignItems: "flex-end", gap: 10 },
  inputAvatar: {
    width: 34, height: 34, borderRadius: 17,
    backgroundColor: Colors.dark.primaryDim, alignItems: "center", justifyContent: "center", flexShrink: 0,
  },
  inputAvatarText: { fontSize: 14, fontFamily: "Inter_700Bold", color: Colors.dark.primary },
  commentInput: {
    flex: 1, backgroundColor: Colors.dark.surfaceLight, borderRadius: 20,
    paddingHorizontal: 14, paddingVertical: 9, fontSize: 14, fontFamily: "Inter_400Regular",
    color: Colors.dark.text, maxHeight: 100, borderWidth: 1, borderColor: Colors.dark.surfaceBorder,
  },
  sendBtn: {
    width: 38, height: 38, borderRadius: 19,
    backgroundColor: Colors.dark.primary, alignItems: "center", justifyContent: "center",
  },
  deactivationMsg: { fontSize: 13, fontFamily: "Inter_400Regular", color: Colors.dark.textMuted, fontStyle: "italic", marginBottom: 10 },
  toggleActiveBtn: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 14, paddingVertical: 9, borderRadius: 12 },
  toggleActiveBtnOn: { backgroundColor: Colors.dark.danger },
  toggleActiveBtnOff: { backgroundColor: Colors.dark.safe },
  toggleActiveBtnText: { fontSize: 13, fontFamily: "Inter_600SemiBold", color: "#fff" },
});
